'use client';
import { useEffect, useMemo, useState } from 'react';
import { Plus, Search, StickyNote, Trash2, X } from 'lucide-react';
import { PageShell } from '@/components/page-shell';
import { deleteNote, listNotes, notePlainText, SavedNote } from '@/lib/notes-store';

export default function MinhasAnotacoesPage(){
  const openNotes=()=>{if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('octa-open-tool',{detail:'notes'}));};
  const [notes,setNotes]=useState<SavedNote[]>([]);const [query,setQuery]=useState('');const [selected,setSelected]=useState<SavedNote|null>(null);
  useEffect(()=>setNotes(listNotes()),[]);
  const filtered=useMemo(()=>{const q=query.toLowerCase().trim();return q?notes.filter(n=>`${n.title} ${n.subject} ${notePlainText(n)} ${n.meetingTitle??''}`.toLowerCase().includes(q)):notes},[notes,query]);
  const remove=(id:string)=>{deleteNote(id);setNotes(listNotes());if(selected?.id===id)setSelected(null)};
  return <PageShell title="Minhas Anotações" kicker="Tudo o que você decidiu, em um só lugar" actions={<div className="flex items-center gap-2"><label className="octa-search !flex !min-w-[250px]"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar anotação"/></label><button onClick={openNotes} className="octa-primary-button"><Plus size={15}/> Nova anotação</button></div>}>
    <div className="grid h-full min-h-0 grid-cols-[1fr_360px] gap-4"><section className="grid min-h-0 content-start grid-cols-3 gap-3 overflow-y-auto pr-1 no-scrollbar">{filtered.length?filtered.map(note=><button key={note.id} onClick={()=>setSelected(note)} className="octa-note-card text-left"><div className="flex items-start justify-between"><span className="grid size-9 place-items-center rounded-xl bg-[#eaf3f5] text-[#0b7285]"><StickyNote size={16}/></span><span className="text-[10px] text-[#8798a5]">{new Date(note.updatedAt).toLocaleDateString('pt-BR')}</span></div><h2 className="mt-4 line-clamp-2 font-semibold text-[#17314a]">{note.title}</h2><p className="mt-2 line-clamp-1 text-[10px] font-medium uppercase tracking-[.08em] text-[#0b7285]">{note.subject||'Sem assunto'}</p><p className="mt-2 line-clamp-3 break-words text-xs leading-5 text-[#6a7f90]">{notePlainText(note)||'Sem conteúdo ainda.'}</p><p className="mt-auto pt-4 text-[10px] text-[#0b7285]">{note.meetingTitle??note.roomSlug??'Anotação geral'}</p></button>):<div className="octa-panel col-span-3 grid h-48 place-items-center text-center text-sm text-[#718494]"><div><StickyNote className="mx-auto mb-3"/><p>Suas anotações salvas aparecerão aqui.</p><button onClick={openNotes} className="mt-4 inline-flex items-center gap-2 text-[#0b7285]"><Plus size={14}/> Criar primeira anotação</button></div></div>}</section>
      <aside className="octa-panel min-h-0 p-5">{selected?<div className="flex h-full flex-col"><div className="flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-[.14em] text-[#0b7285]">Anotação</p><h2 className="mt-1 break-words text-xl font-semibold text-[#17314a]">{selected.title}</h2></div><button onClick={()=>setSelected(null)} className="octa-icon-button"><X size={15}/></button></div><p className="mt-2 text-xs text-[#7a8d9c]">{new Date(selected.updatedAt).toLocaleString('pt-BR')} · {selected.meetingTitle??selected.roomSlug??'Geral'}</p><p className="mt-4 rounded-xl bg-[#eef6f7] px-3 py-2 text-xs font-medium text-[#0b7285]">Assunto: {selected.subject||'Sem assunto'}</p>{selected.format==='html'?<div className="octa-note-detail-rich" dangerouslySetInnerHTML={{__html:selected.content}}/>:<div className="octa-note-detail-rich whitespace-pre-wrap">{selected.content}</div>}<button onClick={()=>remove(selected.id)} className="mt-4 inline-flex items-center justify-center gap-2 rounded-xl border border-rose-200 bg-rose-50 px-4 py-2 text-xs text-rose-600"><Trash2 size={14}/> Excluir anotação</button></div>:<div className="grid h-full place-items-center text-center text-sm text-[#81919e]"><div><StickyNote className="mx-auto mb-3"/><p>Selecione um card para abrir a anotação completa.</p></div></div>}</aside>
    </div></PageShell>;
}
