'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Bell, Bot, Camera, CircleUserRound, LockKeyhole, MessageCircle, Mic, PanelLeftClose, RotateCcw, Settings2, ShieldCheck, Sparkles, Wrench } from 'lucide-react';
import { PageShell } from '@/components/page-shell';

const readPref=(key:string,fallback:boolean)=>{try{const value=localStorage.getItem(key);return value===null?fallback:value==='1'}catch{return fallback}};
const savePref=(key:string,value:boolean)=>{try{localStorage.setItem(key,value?'1':'0')}catch{}};
function Toggle({value,onChange}:{value:boolean;onChange:(value:boolean)=>void}){return <button type="button" aria-pressed={value} onClick={()=>onChange(!value)} className={`h-7 w-12 rounded-full p-1 transition ${value?'bg-black':'bg-black/15'}`}><span className={`block size-5 rounded-full bg-white shadow transition ${value?'translate-x-5':''}`}/></button>}
function Row({icon:Icon,title,text,value,onChange}:{icon:any;title:string;text:string;value?:boolean;onChange?:(value:boolean)=>void}){return <div className="settings-row"><Icon size={19}/><div className="settings-copy flex-1"><b>{title}</b><p>{text}</p></div>{typeof value==='boolean'&&onChange?<Toggle value={value} onChange={onChange}/>:null}</div>}

export default function Page(){
  const[dense,setDense]=useState(false);const[sidebarCollapsed,setSidebarCollapsed]=useState(false);const[chatEnabled,setChatEnabled]=useState(true);const[meetingTools,setMeetingTools]=useState(true);const[aiEnabled,setAiEnabled]=useState(true);const[notifications,setNotifications]=useState(true);const[privacyMode,setPrivacyMode]=useState(true);
  useEffect(()=>{setDense(readPref('octa-compact-mode',false));setSidebarCollapsed(readPref('octa-sidebar-collapsed',false));setChatEnabled(readPref('octa-chat-enabled',true));setMeetingTools(readPref('octa-meeting-tools',true));setAiEnabled(readPref('octa-ai-enabled',true));setNotifications(readPref('octa-notifications',true));setPrivacyMode(readPref('octa-privacy-mode',true))},[]);
  const update=(setter:(value:boolean)=>void,key:string,value:boolean)=>{setter(value);savePref(key,value);window.dispatchEvent(new Event('octa-preferences-updated'))};
  const reset=()=>{try{['octa-sidebar-collapsed','octa-chat-enabled','octa-notes','octa-compact-mode','octa-meeting-tools','octa-ai-enabled','octa-notifications','octa-privacy-mode'].forEach(key=>localStorage.removeItem(key))}catch{}location.reload()};
  return <PageShell title="Configurações" kicker="Conta, reunião, IA e privacidade">
    <div className="grid h-full min-h-0 grid-cols-3 gap-4 overflow-y-auto pr-1 no-scrollbar">
      <section className="octa-panel p-5"><CircleUserRound size={25}/><h2 className="mt-4 text-lg font-semibold">Conta e plano</h2><div className="mt-4 rounded-2xl bg-black p-4 text-white"><p className="text-[10px] uppercase tracking-[.14em] text-white/45">Assinatura atual</p><div className="mt-2 flex items-end justify-between"><div><b className="text-xl">Plano Pro</b><p className="mt-1 text-xs text-white/50">Recursos premium da OCTA.</p></div><Sparkles size={18}/></div></div><div className="mt-3 grid gap-2"><Link href="/profile" className="settings-row"><CircleUserRound size={19}/><div className="settings-copy"><b>Perfil</b><p>Nome, foto e apresentação.</p></div></Link><Link href="/planos" className="settings-row"><ShieldCheck size={19}/><div className="settings-copy"><b>Plano e cobrança</b><p>Ver recursos e opções de assinatura.</p></div></Link></div></section>

      <section className="octa-panel p-5"><Settings2 size={25}/><h2 className="mt-4 text-lg font-semibold">Interface e reunião</h2><div className="mt-4 grid gap-2"><Row icon={PanelLeftClose} title="Barra lateral recolhida" text="Iniciar com o menu lateral compacto." value={sidebarCollapsed} onChange={v=>update(setSidebarCollapsed,'octa-sidebar-collapsed',v)}/><Row icon={Wrench} title="Ferramentas na reunião" text="Calculadora, filtros e anotações visíveis." value={meetingTools} onChange={v=>update(setMeetingTools,'octa-meeting-tools',v)}/><Row icon={MessageCircle} title="Chat ao entrar" text="Abrir a conversa automaticamente." value={chatEnabled} onChange={v=>update(setChatEnabled,'octa-chat-enabled',v)}/><Row icon={Camera} title="Câmera" text="Seleção do dispositivo acontece antes da chamada."/><Row icon={Mic} title="Microfone" text="Seleção do dispositivo acontece antes da chamada."/></div></section>

      <section className="octa-panel p-5"><Bot size={25}/><h2 className="mt-4 text-lg font-semibold">IA, alertas e privacidade</h2><div className="mt-4 grid gap-2"><Row icon={Sparkles} title="OCTA AI" text="Disponibilizar recursos inteligentes no aplicativo." value={aiEnabled} onChange={v=>update(setAiEnabled,'octa-ai-enabled',v)}/><Row icon={Bell} title="Notificações" text="Alertas de reuniões e gravações processadas." value={notifications} onChange={v=>update(setNotifications,'octa-notifications',v)}/><Row icon={LockKeyhole} title="Privacidade reforçada" text="Priorizar análise privada e controles locais." value={privacyMode} onChange={v=>update(setPrivacyMode,'octa-privacy-mode',v)}/><Row icon={ShieldCheck} title="Dados da reunião" text="Gravações e transcrições permanecem vinculadas à sua conta."/></div></section>

      <section className="octa-panel col-span-2 p-5"><h2 className="text-lg font-semibold">Aparência</h2><p className="mt-1 text-sm text-black/45">A OCTA mantém a identidade preto, branco e prata com foco em contraste e legibilidade.</p><div className="mt-4"><Row icon={Settings2} title="Modo compacto" text="Reduzir o espaçamento interno dos painéis." value={dense} onChange={v=>update(setDense,'octa-compact-mode',v)}/></div></section>
      <section className="octa-panel p-5"><RotateCcw size={23}/><h2 className="mt-3 text-lg font-semibold">Restaurar</h2><p className="mt-2 text-xs leading-5 text-black/45">Apaga somente preferências locais deste navegador.</p><button onClick={reset} className="octa-secondary-button mt-4">Restaurar padrão</button></section>
    </div>
  </PageShell>
}
