import assert from 'node:assert/strict';
import { createCalculatorState, applyCalculatorInput } from '../src/lib/calculator.mjs';
let s=createCalculatorState();
s=applyCalculatorInput(s,'12');
s=applyCalculatorInput(s,'.');
s=applyCalculatorInput(s,'5');
assert.equal(s.display,'12.5');
s=applyCalculatorInput(s,'+');
s=applyCalculatorInput(s,'7');
s=applyCalculatorInput(s,'=');
assert.equal(s.display,'19.5');
s=applyCalculatorInput(s,'C');
assert.equal(s.display,'0');
s=applyCalculatorInput(s,'50');
s=applyCalculatorInput(s,'%');
assert.equal(s.display,'0.5');
s=applyCalculatorInput(s,'⌫');
assert.equal(s.display,'0');
console.log('calculator behavior ok');
