// @vitest-environment node
// Regression lock: profile identity comes from OCTA profile and the removed man hero must not return.
import { describe,expect,it } from 'vitest';
import { readFileSync } from 'node:fs';
const read=(path:string)=>readFileSync(path,'utf8');
describe('OCTA AI reference card, profile greeting and audio playback',()=>{
 it('uses the OCTA server profile as the only official AI name source',()=>{const profile=read('src/app/profile/page.tsx');const coach=read('src/components/ai/octa-skill-coach.tsx');expect(profile).toContain("window.dispatchEvent(new CustomEvent('octa-profile:updated'");expect(coach).toContain("fetch('/api/profile',{cache:'no-store'})");expect(coach).toContain('Olá, ${profileName}');expect(coach).toContain("'octa-profile:updated'");expect(coach).not.toContain("localStorage.getItem(PROFILE_NAME_KEY)");expect(coach).not.toContain("localStorage.setItem(PROFILE_NAME_KEY");expect(coach).not.toContain("window.addEventListener('storage'")});
 it('updates the active conversation when the saved profile changes',()=>{const coach=read('src/components/ai/octa-skill-coach.tsx');expect(coach).toContain('replaceProfileName');expect(coach).toContain('previousProfileNameRef');expect(coach).toContain('applyOfficialProfile');expect(coach).toContain('profileName:profileName||undefined');expect(coach).toContain('Fale comigo, ${profileName}...')});
 it('never falls back to the Denner demo identity in profile or home greeting',()=>{const profile=read('src/app/profile/page.tsx');const greeting=read('src/components/profile-greeting.tsx');const store=read('src/lib/profile-store.ts');expect(profile).not.toContain('currentUser.displayName');expect(profile).not.toContain('localStorage.getItem(NAME)');expect(greeting).toContain("fetch('/api/profile',{cache:'no-store'})");expect(greeting).toContain("'octa-profile:updated'");expect(greeting).not.toContain('getProfile()');expect(store).not.toContain("import { currentUser }");expect(store).not.toContain('currentUser.displayName')});
 it('keeps the approved supplied lake hero and blocks the old man asset from returning',()=>{const home=read('src/app/page.tsx');const css=read('src/app/home-reference.module.css');expect(home).toContain('heroPhoto');expect(css).toContain('/octa-hero-lake.webp');expect(home).not.toContain('/octa-hero-man.webp')});
 it('uses the approved animated liquid OCTA AI sphere',()=>{const mark=read('src/components/ai/octa-digital-mark.tsx');expect(mark).toContain('octa-ai-liquid-core');expect(mark).toContain('octa-ai-liquid-wave');expect(mark).toContain('@keyframes octa-ai-liquid-spin');expect(mark).toContain('radial-gradient');expect(mark).not.toContain('viewBox="0 0 32 32"')});
 it('offers listen controls for assistant messages without horizontal chat scrolling',()=>{const coach=read('src/components/ai/octa-skill-coach.tsx');const css=read('src/app/octa-ai-global-voice.css');expect(coach).toContain('Ouvir resposta');expect(coach).toContain('speechSynthesis');expect(coach).toContain('Volume2');expect(css).toContain('overflow-x:hidden');expect(css).toContain('.octa-ai-message-listen')});
 it('keeps the AI panel style while the global liquid orb remains available on home',()=>{const css=read('src/app/octa-ai-global-voice.css');const global=read('src/components/ai/global-octa-ai.tsx');expect(css).toContain('bottom:max(96px');expect(css).toContain('border-radius:24px');expect(css).toContain('.octa-ai-reference-composer');expect(global).toContain('return <OctaSkillCoach/>');expect(global).not.toContain("pathname==='/'")});
});
