// @vitest-environment node
import { describe,expect,it } from 'vitest';
import { readFileSync } from 'node:fs';
const read=(path:string)=>readFileSync(path,'utf8');
describe('OCTA AI reference card, profile greeting and audio playback',()=>{
 it('uses the OCTA server profile as the only official AI name source',()=>{const profile=read('src/app/profile/page.tsx');const coach=read('src/components/ai/octa-skill-coach.tsx');expect(profile).toContain("window.dispatchEvent(new CustomEvent('octa-profile:updated'");expect(coach).toContain("fetch('/api/profile',{cache:'no-store'})");expect(coach).toContain('Olá, ${profileName}');expect(coach).toContain("'octa-profile:updated'");expect(coach).not.toContain("localStorage.getItem(PROFILE_NAME_KEY)");expect(coach).not.toContain("localStorage.setItem(PROFILE_NAME_KEY");expect(coach).not.toContain("window.addEventListener('storage'")});
 it('updates the active conversation when the saved profile changes',()=>{const coach=read('src/components/ai/octa-skill-coach.tsx');expect(coach).toContain('replaceProfileName');expect(coach).toContain('previousProfileNameRef');expect(coach).toContain('applyOfficialProfile');expect(coach).toContain('profileName:profileName||undefined');expect(coach).toContain('Fale comigo, ${profileName}...')});
 it('uses a clean geometric OCTA mark instead of the previous multi-piece symbol',()=>{const mark=read('src/components/ai/octa-digital-mark.tsx');expect(mark).toContain('<svg');expect(mark).toContain('viewBox="0 0 32 32"');expect(mark).toContain('<circle');expect(mark).not.toContain('<i/>');expect(mark).not.toContain('<em/>')});
 it('offers listen controls for assistant messages without horizontal chat scrolling',()=>{const coach=read('src/components/ai/octa-skill-coach.tsx');const css=read('src/app/octa-ai-global-voice.css');expect(coach).toContain('Ouvir resposta');expect(coach).toContain('speechSynthesis');expect(coach).toContain('Volume2');expect(css).toContain('overflow-x:hidden');expect(css).toContain('.octa-ai-message-listen')});
 it('matches the supplied dark reference card language and keeps launcher out of controls',()=>{const css=read('src/app/octa-ai-global-voice.css');expect(css).toContain('bottom:max(96px');expect(css).toContain('border-radius:24px');expect(css).toContain('linear-gradient(180deg,#1c1d1f');expect(css).toContain('.octa-ai-reference-composer');expect(css).toContain('.octa-ai-orb .octa-ai-mark')});
});
