'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowRight, ChevronRight, Play, Search, Sparkles, TrendingUp } from 'lucide-react';
import { PageShell } from '@/components/page-shell';
import { octaSkillsSnapshot } from '@/lib/octa-ai-context';
type Tab='visao'|'transcricao'|'treino'|'evolucao';
const meetings=[['Planejamento de Marketing','88'],['Reunião Semanal da Diretoria','84'],['Laboratório de Marca','79']];
const transcript=[['14:32','Você','Precisamos entender primeiro qual resultado vocês querem alcançar.'],['14:34','Amanda','Nosso problema hoje é principalmente aquisição.'],['14:35','Você','Quanto isso representa atualmente para vocês?']];
const performance=Object.entries(octaSkillsSnapshot.competencies) as [string,number][];
export default function SkillsPage(){const[tab,setTab]=useState<Tab>('visao');return <PageShell title="Octa skills" kicker="Cada reunião vira aprendizado prático" actions={<div className="flex items-center gap-2"><span className="skills-private">Análise privada</span><Link href="/reunioes" className="skills-dark-link">Ver reuniões <ChevronRight size={13}/></Link></div>}><div className="skills-shell skills-reference-shell"><nav className="skills-tabs skills-reference-tabs">{([['visao','Visão geral'],['transcricao','Transcrição'],['treino','Treino'],['evolucao','Evolução']] as [Tab,string][]).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'is-active':''}>{label}</button>)}</nav><div className="skills-body">{tab==='visao'&&<Overview/>}{tab==='transcricao'&&<Transcript/>}{tab==='treino'&&<Training/>}{tab==='evolucao'&&<Evolution/>}</div></div></PageShell>}

function Overview(){return <div className="skills-performance-dashboard">
  <section className="skills-dash-card skills-dash-score"><div className="skills-dash-label">Performance geral</div><div className="skills-score-row"><strong>{octaSkillsSnapshot.score}</strong><span>/100</span><i><TrendingUp size={13}/> {octaSkillsSnapshot.weeklyChange}</i></div><p>Consistência em clareza e perguntas. O maior ganho desta semana veio de objetividade.</p><div className="skills-mini-evidence"><span><b>8</b> reuniões</span><span><b>6</b> alta evidência</span></div></section>
  <section className="skills-dash-card skills-dash-metrics"><div className="skills-dash-head"><div><span>Competências</span><h3>Performance por habilidade</h3></div><small>evidência da transcrição</small></div><div className="skills-skill-grid">{performance.map(([name,value])=><div className="skills-skill-row" key={name}><div><span>{name}</span><strong>{value}</strong></div><div className="skills-skill-track"><i style={{width:`${value}%`}}/></div></div>)}</div></section>
  <section className="skills-dash-card skills-dash-trend"><div className="skills-dash-head"><div><span>Desempenho semanal</span><h3>{octaSkillsSnapshot.score}/100</h3></div><small>últimas 7 reuniões</small></div><PerformanceTrend/><div className="skills-trend-legend"><span>68</span><span>72</span><span>76</span><span>79</span><span>78</span><span>80</span><b>82</b></div></section>
  <section className="skills-dash-card skills-dash-goal"><div className="skills-dash-label">Meta de evolução</div><div className="skills-goal-ring" style={{background:'conic-gradient(#59bfe0 0 91%, rgba(255,255,255,.08) 91% 100%)'}}><div><strong>91%</strong><span>da meta</span></div></div><p><b>{octaSkillsSnapshot.score}</b> de {octaSkillsSnapshot.target} pontos</p><small>+8 pontos restantes</small></section>
  <section className="skills-dash-card skills-dash-recent"><div className="skills-dash-head"><div><span>Histórico</span><h3>Últimas reuniões</h3></div><Link href="/reunioes">Ver todas <ChevronRight size={12}/></Link></div>{meetings.map(([name,score],i)=><div className="skills-meeting-row" key={name}><span><i>{i+1}</i>{name}</span><strong>{score}</strong></div>)}</section>
  <section className="skills-dash-card skills-dash-strength"><div className="skills-dash-label">Pontos fortes</div><h3>Você investiga antes de oferecer.</h3><p>Confirmou entendimento antes de avançar e manteve a conversa contextualizada.</p><button>Ver evidências <ArrowRight size={14}/></button></section>
  <section className="skills-dash-card skills-dash-opportunity"><div className="skills-dash-label">Oportunidade</div><h3>Ganhar objetividade nas objeções.</h3><p>A resposta sobre preço demorou para chegar ao ponto central. Meta: reduzir 18% do tempo de resposta.</p><button>Rever momento <Play size={13}/></button></section>
  <section className="skills-dash-card skills-dash-map"><div className="skills-dash-head"><div><span>Mapa de performance</span><h3>Equilíbrio das competências</h3></div><small>média 85</small></div><div className="skills-map-content"><svg viewBox="0 0 180 150" aria-label="Mapa visual das competências"><g fill="none" stroke="rgba(255,255,255,.09)"><polygon points="90,10 158,48 146,122 90,144 34,122 22,48"/><polygon points="90,32 139,58 130,110 90,126 50,110 41,58"/><polygon points="90,54 121,69 116,98 90,108 64,98 59,69"/></g><polygon points="90,20 151,50 136,113 90,133 45,113 31,54" fill="rgba(74,192,216,.13)" stroke="#65cee2" strokeWidth="2"/><g fill="#8fe3ee">{[[90,20],[151,50],[136,113],[90,133],[45,113],[31,54]].map(([x,y])=><circle key={`${x}-${y}`} cx={x} cy={y} r="3"/>)}</g></svg><div className="skills-map-deltas"><span><b>+12</b> Perguntas</span><span><b>+9</b> Objetividade</span><span><b>+7</b> Clareza</span></div></div></section>
</div>}
function PerformanceTrend(){return <svg className="skills-trend-chart" viewBox="0 0 360 120" role="img" aria-label="Evolução semanal de performance"><defs><linearGradient id="skillArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#55c6e2" stopOpacity=".30"/><stop offset="1" stopColor="#55c6e2" stopOpacity="0"/></linearGradient></defs><path d="M8 96 C45 90,55 79,70 77 S112 67,126 65 S168 48,184 52 S220 39,242 43 S290 29,352 22 L352 116 L8 116 Z" fill="url(#skillArea)"/><path d="M8 96 C45 90,55 79,70 77 S112 67,126 65 S168 48,184 52 S220 39,242 43 S290 29,352 22" fill="none" stroke="#62c9e3" strokeWidth="3" strokeLinecap="round"/><g fill="#07121d" stroke="#8be3f2" strokeWidth="2">{[[8,96],[70,77],[126,65],[184,52],[242,43],[294,34],[352,22]].map(([x,y])=><circle key={x} cx={x} cy={y} r="4"/>)}</g></svg>}
function Transcript(){return <div className="skills-reference-transcricao skills-reference-grid"><section className="skills-reference-card skills-feature"><p className="skills-eyebrow">TRANSCRIÇÃO INTELIGENTE</p><h2>Planejamento de Marketing</h2><div className="skills-search-dark"><Search size={15}/><span>Pesquisar nesta reunião...</span></div>{transcript.map(([t,s,x])=><div className="skills-line" key={t}><small>{t}</small><strong>{s}</strong><p>{x}</p></div>)}</section><section className="skills-reference-card skills-coach"><Sparkles/><p className="skills-eyebrow">OCTA SUGERE</p><h3>Como eu poderia ter dito?</h3><blockquote>“Antes de avançarmos, quero entender exatamente o impacto desse ponto e o que precisa acontecer para resolvermos isso.”</blockquote><button>Ver momento <Play size={14}/></button></section><Insight title="Clareza da conversa" text="91/100 · Suas perguntas mantiveram o contexto e reduziram ambiguidades." action="Ver evidências"/><Insight title="Momento-chave" text="14:35 · A pergunta de impacto abriu espaço para uma resposta mais objetiva." action="Rever momento"/></div>}
function Training(){return <div className="skills-reference-treino skills-reference-grid"><section className="skills-reference-card skills-feature"><p className="skills-eyebrow">TREINO · 41:08</p><h2>Treinar este momento</h2><p className="skills-lead">Amanda disse: “O investimento ficou acima do que imaginávamos.”</p><div className="skills-simulation"><small>OCTA assume o papel de Amanda</small><strong>Pratique uma nova resposta sem sair do contexto da reunião.</strong></div><button className="skills-blue-button">Iniciar simulação <ArrowRight size={15}/></button></section><section className="skills-reference-card skills-score"><span>Performance no treino</span><strong>86</strong><small>/100</small><p>Você investigou a origem da objeção antes de defender o preço.</p></section><Insight title="Objetivo do treino" text="Chegar ao ponto central com menos palavras e uma pergunta de diagnóstico." action="Ver orientação"/><Insight title="Próximo passo" text="Repita a simulação até sustentar clareza acima de 90 por três tentativas." action="Treinar novamente"/></div>}
function Evolution(){return <div className="skills-reference-evolucao skills-reference-grid"><section className="skills-reference-card skills-feature"><p className="skills-eyebrow">EVOLUÇÃO</p><h2>Últimas 10 reuniões</h2>{[['Clareza','72 → 84'],['Objetividade','68 → 81'],['Perguntas de diagnóstico','61 → 79'],['Interrupções','9 → 4']].map(([a,b])=><div className="skills-metric" key={a}><span>{a}</span><strong>{b}</strong></div>)}</section><Goal/><Recent/><Insight title="Maior avanço" text="Objetividade cresceu de forma consistente nas últimas quatro reuniões." action="Ver evolução"/></div>}
function Goal(){return <section className="skills-reference-card skills-reference-goal"><h3>Meta de evolução</h3><p>Chegar a 90 de performance</p><strong>82 / 90</strong><div className="skills-reference-progress"><i/></div><div className="skills-reference-card-foot"><span>91% da meta</span><span>+8 pontos restantes</span></div></section>}
function Recent(){return <section className="skills-reference-card skills-reference-recent"><h3>Últimas reuniões</h3>{meetings.map(([a,b])=><div className="skills-reference-meeting" key={a}><span>{a}</span><strong>{b}</strong></div>)}</section>}
function Insight({title,text,action}:{title:string;text:string;action:string}){return <section className="skills-reference-card skills-reference-insight"><h3>{title}</h3><p>{text}</p><button>{action} <ArrowRight size={16}/></button></section>}
