'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ChevronDown, Eye, Image as ImageIcon, Laptop, Monitor, Moon, Move, Redo2, RotateCcw, Save, Smartphone, Sun, Tablet, Type, Undo2, Upload, WandSparkles } from 'lucide-react';
import { CmsBreakpoint, CmsDocument, CmsElementOverride, CmsTheme, EMPTY_CMS_DOCUMENT, getCmsScopeKey, sanitizeCmsDocument, sanitizeCmsPatch } from '@/lib/cms';

type Selected={id:string;type:string;tag:string;text:string;href:string;src:string;alt:string;placeholder?:string;rect:{x:number;y:number;width:number;height:number};computed:Record<string,string>};
type Layer={id:string;type:string;label:string};
const ROUTES=[['/','Início'],['/agenda','Agenda'],['/reunioes','Reuniões'],['/contatos','Contatos'],['/feed','Feed'],['/gravacoes','Gravações'],['/skills','Octa skills'],['/configuracoes','Configurações'],['/room/strategy-room','Sala de reunião']];
const VIEWPORTS:Record<CmsBreakpoint,{label:string;width:number;icon:any}>={desktop:{label:'Desktop',width:1512,icon:Monitor},notebook:{label:'Notebook',width:1280,icon:Laptop},tablet:{label:'Tablet',width:820,icon:Tablet},mobile:{label:'Mobile',width:390,icon:Smartphone}};
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));

export function CmsEditor(){
 const [route,setRoute]=useState('/');const[theme,setTheme]=useState<CmsTheme>('light');const[breakpoint,setBreakpoint]=useState<CmsBreakpoint>('desktop');const[doc,setDoc]=useState<CmsDocument>(EMPTY_CMS_DOCUMENT);const[selected,setSelected]=useState<Selected|null>(null);const[layers,setLayers]=useState<Layer[]>([]);const[history,setHistory]=useState<any[]>([]);const[status,setStatus]=useState('Carregando…');const[past,setPast]=useState<CmsDocument[]>([]);const[future,setFuture]=useState<CmsDocument[]>([]);const[tab,setTab]=useState<'content'|'type'|'layout'|'appearance'|'media'>('content');const iframe=useRef<HTMLIFrameElement>(null);
 const scope=getCmsScopeKey(route,theme,breakpoint); const active=selected?doc.scopes[scope]?.[selected.id]||{}:{};
 const previewUrl=useMemo(()=>`${route}${route.includes('?')?'&':'?'}cmsPreview=1`,[route]);
 const send=useCallback((type:string,payload:any={})=>iframe.current?.contentWindow?.postMessage({type:`octa:cms:${type}`,...payload},location.origin),[]);
 useEffect(()=>{Promise.all([fetch('/api/cms?status=draft').then(r=>r.json()),fetch('/api/cms?status=history').then(r=>r.json())]).then(([draft,h])=>{setDoc(sanitizeCmsDocument(draft.document));setHistory(h.items||[]);setStatus('Rascunho carregado')}).catch(()=>setStatus('Falha ao carregar'))},[]);
 useEffect(()=>{const onMessage=(event:MessageEvent)=>{if(event.origin!==location.origin||!event.data?.type?.startsWith('octa:cms:'))return;if(event.data.type==='octa:cms:ready'){send('document',{document:doc});send('theme',{theme});send('requestLayers')}if(event.data.type==='octa:cms:select'){setSelected(event.data.element)}if(event.data.type==='octa:cms:layers'){setLayers(event.data.layers||[])}if(event.data.type==='octa:cms:change'){update(event.data.patch,event.data.id,false)}};addEventListener('message',onMessage);return()=>removeEventListener('message',onMessage)});
 useEffect(()=>{send('document',{document:doc});send('theme',{theme});},[doc,theme,send]);
 function pushUndo(){setPast(p=>[...p.slice(-39),clone(doc)]);setFuture([])}
 function update(patch:CmsElementOverride,id=selected?.id,record=true){if(!id)return;if(record)pushUndo();const clean=sanitizeCmsPatch(patch);setDoc(current=>{const next=clone(current);next.scopes[scope]??={};next.scopes[scope][id]={...(next.scopes[scope][id]||{}),...clean,style:{...(next.scopes[scope][id]?.style||{}),...(clean.style||{})}};next.updatedAt=new Date().toISOString();return next})}
 function setStyle(key:string,value:string){update({style:{[key]:value}})}
 function undo(){const prev=past.at(-1);if(!prev)return;setFuture(f=>[clone(doc),...f]);setDoc(prev);setPast(p=>p.slice(0,-1))}
 function redo(){const next=future[0];if(!next)return;setPast(p=>[...p,clone(doc)]);setDoc(next);setFuture(f=>f.slice(1))}
 async function save(action:'saveDraft'|'publish'){setStatus(action==='publish'?'Publicando…':'Salvando…');const r=await fetch('/api/cms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,document:doc})});const data=await r.json();setStatus(r.ok?(action==='publish'?'Publicado':'Rascunho salvo'):(data.error||'Erro'));if(r.ok){const h=await fetch('/api/cms?status=history').then(x=>x.json());setHistory(h.items||[])}}
 async function restore(id:string){const r=await fetch('/api/cms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'restore',revisionId:id})});const d=await r.json();if(r.ok&&d.document){pushUndo();setDoc(sanitizeCmsDocument(d.document));setStatus('Versão restaurada como rascunho')}}
 function resetElement(){if(!selected)return;pushUndo();setDoc(c=>{const n=clone(c);if(n.scopes[scope])delete n.scopes[scope][selected.id];return n});setSelected(null)}
 function resetRoute(){pushUndo();setDoc(c=>{const n=clone(c);for(const key of Object.keys(n.scopes))if(key.startsWith(`${route}::`)|| (route==='/'&&key.startsWith('/::')))delete n.scopes[key];return n})}
 function resetAll(){pushUndo();setDoc(EMPTY_CMS_DOCUMENT);setSelected(null)}
 return <main className="cms-admin-shell">
   <header className="cms-admin-topbar"><div className="cms-brand"><a href="/" title="Voltar ao OCTA"><ArrowLeft size={17}/></a><strong>OCTA CMS</strong><span>{status}</span></div><div className="cms-toolbar"><button onClick={undo} disabled={!past.length}><Undo2 size={15}/> Undo</button><button onClick={redo} disabled={!future.length}><Redo2 size={15}/> Redo</button><div className="cms-segment">{(Object.entries(VIEWPORTS) as [CmsBreakpoint,any][]).map(([id,v])=>{const I=v.icon;return <button key={id} onClick={()=>setBreakpoint(id)} className={breakpoint===id?'is-active':''} title={v.label}><I size={15}/><span>{v.label}</span></button>})}</div><div className="cms-segment"><button onClick={()=>setTheme('light')} className={theme==='light'?'is-active':''}><Sun size={15}/> Claro</button><button onClick={()=>setTheme('dark')} className={theme==='dark'?'is-active':''}><Moon size={15}/> Escuro</button></div><button onClick={()=>save('saveDraft')}><Save size={15}/> Salvar rascunho</button><button className="cms-publish" onClick={()=>save('publish')}><WandSparkles size={15}/> Publicar</button></div></header>
   <aside className="cms-left"><div className="cms-panel-title"><b>Páginas</b><Eye size={15}/></div><div className="cms-page-list">{ROUTES.map(([href,label])=><button key={href} onClick={()=>{setRoute(href);setSelected(null)}} className={route===href?'is-active':''}><span>{label}</span><small>{href}</small></button>)}</div><div className="cms-panel-title"><b>Camadas</b><Move size={15}/></div><div className="cms-layer-list">{layers.map(l=><button key={l.id} onClick={()=>{send('selectById',{id:l.id})}}><span>{l.label||l.id}</span><small>{l.type}</small></button>)}</div><details className="cms-history"><summary>Histórico <ChevronDown size={14}/></summary>{history.map(h=><button key={h.id} onClick={()=>restore(h.id)}><span>{h.status}</span><small>{new Date(h.created_at).toLocaleString('pt-BR')}</small></button>)}</details></aside>
   <section className="cms-stage"><div className="cms-canvas" style={{width:VIEWPORTS[breakpoint].width}}><iframe ref={iframe} key={`${route}-${breakpoint}`} src={previewUrl} title="OCTA preview"/></div><div className="cms-stage-caption">{VIEWPORTS[breakpoint].label} · {VIEWPORTS[breakpoint].width}px · {theme==='dark'?'Escuro':'Claro'}</div></section>
   <aside className="cms-inspector"><div className="cms-inspector-head"><div><small>Selecionado</small><strong>{selected?.id||'Clique em um elemento'}</strong></div>{selected&&<button onClick={resetElement}><RotateCcw size={14}/></button>}</div>{selected?<><div className="cms-tabs"><button onClick={()=>setTab('content')} className={tab==='content'?'is-active':''}>Conteúdo</button><button onClick={()=>setTab('type')} className={tab==='type'?'is-active':''}>Tipografia</button><button onClick={()=>setTab('layout')} className={tab==='layout'?'is-active':''}>Layout</button><button onClick={()=>setTab('appearance')} className={tab==='appearance'?'is-active':''}>Aparência</button><button onClick={()=>setTab('media')} className={tab==='media'?'is-active':''}>Mídia</button></div>
   {tab==='content'&&<div className="cms-controls">{(selected.type==='text'||selected.tag==='a'||selected.tag==='button')&&<Field label="Texto"><textarea value={active.text??selected.text} onChange={e=>update({text:e.target.value})}/></Field>}{selected.tag==='a'&&<Field label="Link"><input value={active.href??selected.href} onChange={e=>update({href:e.target.value})}/></Field>}{(selected.tag==='input'||selected.tag==='textarea')&&<Field label="Placeholder"><input value={active.placeholder??selected.placeholder??''} onChange={e=>update({placeholder:e.target.value})}/></Field>}<Toggle label="Ocultar elemento" checked={active.hidden===true} onChange={v=>update({hidden:v})}/></div>}
   {tab==='type'&&<div className="cms-controls"><Field label="Fonte"><input value={String(active.style?.fontFamily??selected.computed.fontFamily)} onChange={e=>setStyle('fontFamily',e.target.value)}/></Field><Two><Field label="Tamanho"><input value={String(active.style?.fontSize??selected.computed.fontSize)} onChange={e=>setStyle('fontSize',e.target.value)}/></Field><Field label="Peso"><input value={String(active.style?.fontWeight??selected.computed.fontWeight)} onChange={e=>setStyle('fontWeight',e.target.value)}/></Field></Two><Two><Field label="Altura linha"><input value={String(active.style?.lineHeight??selected.computed.lineHeight)} onChange={e=>setStyle('lineHeight',e.target.value)}/></Field><Field label="Espaçamento"><input value={String(active.style?.letterSpacing??selected.computed.letterSpacing)} onChange={e=>setStyle('letterSpacing',e.target.value)}/></Field></Two><Field label="Cor"><input type="color" value={toHex(String(active.style?.color??selected.computed.color))} onChange={e=>setStyle('color',e.target.value)}/></Field></div>}
   {tab==='layout'&&<div className="cms-controls"><div className="cms-position-mode"><button onClick={()=>update({positionMode:'flow',style:{transform:'none'}})} className={active.positionMode!=='free'?'is-active':''}>Fluxo</button><button onClick={()=>update({positionMode:'free'})} className={active.positionMode==='free'?'is-active':''}>Livre</button></div><Two><Field label="Largura"><input value={String(active.style?.width??Math.round(selected.rect.width)+'px')} onChange={e=>setStyle('width',e.target.value)}/></Field><Field label="Altura"><input value={String(active.style?.height??Math.round(selected.rect.height)+'px')} onChange={e=>setStyle('height',e.target.value)}/></Field></Two><Field label="Transform / posição"><input value={String(active.style?.transform??'none')} onChange={e=>setStyle('transform',e.target.value)}/></Field><Two><Field label="Padding"><input value={String(active.style?.padding??selected.computed.padding)} onChange={e=>setStyle('padding',e.target.value)}/></Field><Field label="Margin"><input value={String(active.style?.margin??selected.computed.margin)} onChange={e=>setStyle('margin',e.target.value)}/></Field></Two><Field label="Z-index"><input value={String(active.style?.zIndex??'auto')} onChange={e=>setStyle('zIndex',e.target.value)}/></Field></div>}
   {tab==='appearance'&&<div className="cms-controls"><Field label="Fundo"><input value={String(active.style?.background??active.style?.backgroundColor??selected.computed.backgroundColor)} onChange={e=>setStyle('background',e.target.value)}/></Field><Two><Field label="Borda"><input value={String(active.style?.border??`${selected.computed.borderWidth} solid ${selected.computed.borderColor}`)} onChange={e=>setStyle('border',e.target.value)}/></Field><Field label="Raio"><input value={String(active.style?.borderRadius??selected.computed.borderRadius)} onChange={e=>setStyle('borderRadius',e.target.value)}/></Field></Two><Field label="Sombra / luz"><input value={String(active.style?.boxShadow??selected.computed.boxShadow)} onChange={e=>setStyle('boxShadow',e.target.value)}/></Field><Two><Field label="Opacidade"><input value={String(active.style?.opacity??selected.computed.opacity)} onChange={e=>setStyle('opacity',e.target.value)}/></Field><Field label="Filtro"><input value={String(active.style?.filter??'none')} onChange={e=>setStyle('filter',e.target.value)}/></Field></Two></div>}
   {tab==='media'&&<div className="cms-controls"><Field label="URL da foto/vídeo"><div className="cms-media-input"><ImageIcon size={15}/><input value={String(active.src??selected.src)} onChange={e=>update({src:e.target.value})}/></div></Field><button className="cms-upload-button" onClick={()=>document.getElementById('cms-media-file')?.click()}><Upload size={15}/> Substituir arquivo</button><input id="cms-media-file" hidden type="file" accept="image/*,video/*" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;const fd=new FormData();fd.append('file',f);const r=await fetch('/api/cms/assets',{method:'POST',body:fd});const d=await r.json();if(r.ok)update({src:d.url})}}/><Two><Field label="Ajuste"><select value={String(active.style?.objectFit??selected.computed.objectFit||'cover')} onChange={e=>setStyle('objectFit',e.target.value)}><option>cover</option><option>contain</option><option>fill</option><option>none</option></select></Field><Field label="Foco"><input value={String(active.style?.objectPosition??selected.computed.objectPosition||'50% 50%')} onChange={e=>setStyle('objectPosition',e.target.value)}/></Field></Two><Field label="Alt text"><input value={String(active.alt??selected.alt)} onChange={e=>update({alt:e.target.value})}/></Field></div>}
   <div className="cms-reset-row"><button onClick={resetRoute}>Resetar página</button><button onClick={resetAll}>Resetar tudo</button></div></>:<div className="cms-empty"><Type size={28}/><p>Clique em qualquer texto, card, imagem, botão ou bloco do preview para editar.</p></div>}</aside>
 </main>
}
function Field({label,children}:{label:string;children:any}){return <label className="cms-field"><span>{label}</span>{children}</label>}
function Two({children}:{children:any}){return <div className="cms-two">{children}</div>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="cms-toggle"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><i/></label>}
function toHex(v:string){if(v.startsWith('#'))return v.slice(0,7);const m=v.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);if(!m)return '#0a2238';return '#'+[m[1],m[2],m[3]].map(x=>Number(x).toString(16).padStart(2,'0')).join('')}
