'use client';
import Link from 'next/link';import { useEffect,useState } from 'react';import { usePathname,useRouter } from 'next/navigation';import { Bell,Brush,Calculator,CalendarDays,ChevronRight,CircleUserRound,FileImage,FileText,Filter,Gem,Home,Maximize2,Menu,Minimize2,NotebookPen,Pencil,Play,Search,Sparkles,UsersRound,VideoIcon } from 'lucide-react';import { useToolOverlay } from '@/components/tool-overlay-context';import { ProfileEditor } from '@/components/profile-editor';import { defaultEditableProfile,EditableProfile,getProfile,PROFILE_UPDATED_EVENT } from '@/lib/profile-store';
const topItems=[{href:'/',label:'Início'},{href:'/reunioes',label:'Reuniões'},{href:'/agenda',label:'Agenda'},{href:'/planos',label:'Planos e preços'}];
const sidePrimary=[{href:'/',label:'Início',icon:Home},{href:'/reunioes',label:'Reuniões',icon:VideoIcon},{href:'/agenda',label:'Agenda',icon:CalendarDays},{href:'/contatos',label:'Contatos',icon:UsersRound},{href:'/gravacoes',label:'Gravações',icon:VideoIcon}];
const sideUtility=[{href:'/filtros',label:'Filtros',icon:Filter},{href:'/lousa',label:'Lousa',icon:Brush},{href:'/minhas-anotacoes',label:'Minhas Anotações',icon:FileText},{href:'/skills',label:'Skill',icon:Sparkles}];
export function OctaLogo(){return <Link href="/" className="octa-wordmark" aria-label="OCTA início">OCTA</Link>}

function PresentationEscBridge(){
 const[live,setLive]=useState(false);const[paused,setPaused]=useState(false);const[compact,setCompact]=useState(false);
 useEffect(()=>{const sync=()=>{const active=Boolean(document.querySelector('.presentation-live-shell'));setLive(active);if(!active){setPaused(false);setCompact(false);document.documentElement.classList.remove('octa-presentation-paused','octa-pips-compact')}};sync();const observer=new MutationObserver(sync);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[]);
 useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'&&live&&!paused){event.preventDefault();setPaused(true)}};window.addEventListener('keydown',onKey,true);return()=>window.removeEventListener('keydown',onKey,true)},[live,paused]);
 useEffect(()=>{document.documentElement.classList.toggle('octa-presentation-paused',paused);return()=>document.documentElement.classList.remove('octa-presentation-paused')},[paused]);
 useEffect(()=>{document.documentElement.classList.toggle('octa-pips-compact',compact&&live);return()=>document.documentElement.classList.remove('octa-pips-compact')},[compact,live]);
 if(!live)return null;
 if(paused)return <div className="octa-slide-paused" style={{zIndex:2147483600}}><div><small>SLIDE PAUSADO</small><b>O slide atual foi preservado</b><span>Continue explicando em vídeo e retome no mesmo ponto.</span></div><button onClick={()=>setPaused(false)}><Play size={15}/>Retomar em Full HD</button></div>;
 return <button className="octa-pip-compact-toggle" style={{zIndex:2147483600}} onClick={()=>setCompact(v=>!v)}>{compact?<Maximize2 size={14}/>:<Minimize2 size={14}/>} {compact?'Expandir vídeos':'Encolher vídeos'}</button>;
}

export function DashboardSidebar({collapsed=false,onToggle}:{collapsed?:boolean;onToggle?:()=>void}){const path=usePathname();const router=useRouter();const{openTool}=useToolOverlay();const[profile,setProfile]=useState<EditableProfile>(defaultEditableProfile);const[editing,setEditing]=useState(false);
 useEffect(()=>{setProfile(getProfile());const onUpdate=(e:Event)=>setProfile((e as CustomEvent<EditableProfile>).detail??getProfile());window.addEventListener(PROFILE_UPDATED_EVENT,onUpdate);return()=>window.removeEventListener(PROFILE_UPDATED_EVENT,onUpdate)},[]);
 const triggerSlides=()=>{const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>('button'));const share=buttons.find(button=>button.textContent?.trim()==='Compartilhar');if(share){share.click();try{localStorage.removeItem('octa-open-slides')}catch{}return true}return false};
 useEffect(()=>{if(path!=='/reuniao-instantanea')return;let shouldOpen=false;try{shouldOpen=localStorage.getItem('octa-open-slides')==='1'}catch{}if(!shouldOpen)return;let attempts=0;const timer=window.setInterval(()=>{attempts+=1;if(triggerSlides()||attempts>30)window.clearInterval(timer)},100);return()=>window.clearInterval(timer)},[path]);
 const openSlides=()=>{try{localStorage.setItem('octa-open-slides','1')}catch{}if(path==='/reuniao-instantanea'){window.setTimeout(()=>triggerSlides(),0);return}router.push('/reuniao-instantanea')};
 const item=(href:string,label:string,Icon:any)=>{const cleanHref=href.split('?')[0];return <Link key={`${href}-${label}`} href={href} title={collapsed?label:undefined} className={`octa-side-item ${path===cleanHref?'is-active':''}`}><Icon size={19}/><span className="octa-side-label">{label}</span></Link>};const tool=(label:string,Icon:any,kind:'calculator'|'notes')=><button key={kind} onClick={()=>openTool(kind)} title={collapsed?label:undefined} className="octa-side-item w-full text-left"><Icon size={19}/><span className="octa-side-label">{label}</span></button>;
 return <><aside className={`octa-sidebar hidden xl:flex ${collapsed?'is-collapsed':''}`} style={{background:'linear-gradient(180deg,rgba(5,8,10,.985),rgba(8,10,11,.98))'}}>
  <div className="agenda-side-brand"><span className="agenda-side-ring"/><span className="octa-side-label">OCTA</span></div>
  <div className="octa-profile flex items-center gap-3 px-5 pt-4"><div className="relative size-12 shrink-0 overflow-hidden rounded-full border border-white/30 bg-white/15"><img src={profile.avatarUrl} alt={profile.displayName} className="h-full w-full object-cover"/><span className="absolute bottom-0 right-0 size-3 rounded-full border-2 border-black bg-emerald-400"/></div><div className="octa-profile-copy min-w-0 flex-1"><div className="truncate text-[17px] font-medium text-white">{profile.displayName}</div><div className="mt-0.5 truncate text-xs text-white/55">{profile.headline}</div></div>{!collapsed&&<button onClick={()=>setEditing(true)} className="grid size-8 shrink-0 place-items-center rounded-full bg-white/8 text-white/55"><Pencil size={14}/></button>}</div>
  {!collapsed&&<div className="agenda-skill-meter"><div><span>Performance do skills</span><b>82/100</b></div><i><em/></i></div>}
  <nav className="octa-side-nav no-scrollbar overflow-y-auto">{sidePrimary.map(({href,label,icon})=>item(href,label,icon))}<div className="octa-side-divider"/>{tool('Calculadora',Calculator,'calculator')}{sideUtility.slice(0,1).map(({href,label,icon})=>item(href,label,icon))}<button onClick={openSlides} title={collapsed?'Montar slides':undefined} className="octa-side-item w-full text-left"><FileImage size={19}/><span className="octa-side-label">Montar slides</span></button>{tool('Anotar',NotebookPen,'notes')}{sideUtility.slice(1).map(({href,label,icon})=>item(href,label,icon))}</nav>
  <div className="agenda-plan-card"><Gem size={23}/><div className="octa-side-label"><b>Plano Pro</b><span>Renova em 12 dias</span></div><ChevronRight className="octa-side-label" size={18}/></div><button onClick={onToggle} className="octa-expand-orb"><ChevronRight size={19}/></button>
  <style jsx global>{`
    .agenda-side-brand{display:flex;align-items:center;gap:13px;padding:26px 28px 15px;color:#fff;font-size:23px;font-weight:390;letter-spacing:.08em}.agenda-side-ring{width:38px;height:38px;border:3px solid rgba(255,255,255,.92);border-right-color:rgba(255,255,255,.35);border-radius:50%;box-shadow:inset 0 0 0 2px rgba(255,255,255,.08)}
    .agenda-skill-meter{padding:25px 22px 12px;color:#fff;font-size:11px}.agenda-skill-meter>div{display:flex;justify-content:space-between;color:rgba(255,255,255,.72)}.agenda-skill-meter b{font-weight:500;color:#fff}.agenda-skill-meter i{display:block;height:6px;margin-top:9px;border-radius:99px;background:rgba(255,255,255,.13);overflow:hidden}.agenda-skill-meter em{display:block;width:82%;height:100%;border-radius:inherit;background:linear-gradient(90deg,#f3b16d,#d79b6a)}
    .octa-sidebar .octa-side-nav{margin-top:16px!important;padding:0 20px!important}.octa-sidebar .octa-side-item{height:50px!important;border-radius:16px!important;font-size:15px!important;color:rgba(255,255,255,.87)!important}.octa-sidebar .octa-side-item.is-active{background:rgba(255,255,255,.11)!important;box-shadow:none!important}.octa-sidebar .octa-side-item.is-active::before{display:none!important}.octa-sidebar .octa-side-divider{margin:8px 0!important;border-color:rgba(255,255,255,.08)!important}
    .agenda-plan-card{margin:0 20px 22px;padding:18px 14px;border-top:1px solid rgba(255,255,255,.08);display:flex;align-items:center;gap:12px;color:#fff}.agenda-plan-card>div{display:flex;min-width:0;flex:1;flex-direction:column}.agenda-plan-card b{font-size:14px;font-weight:520}.agenda-plan-card span{margin-top:2px;font-size:10px;color:rgba(255,255,255,.62)}.octa-sidebar .octa-expand-orb{position:absolute!important;right:12px!important;bottom:14px!important;width:34px!important;height:34px!important;background:rgba(255,255,255,.08)!important;box-shadow:none!important}.octa-sidebar.is-collapsed .agenda-side-brand{justify-content:center;padding:22px 0}.octa-sidebar.is-collapsed .agenda-side-ring{width:34px;height:34px}.octa-sidebar.is-collapsed .agenda-plan-card{justify-content:center;margin:0 12px 55px;padding:16px 0}.octa-sidebar.is-collapsed .agenda-plan-card>svg{width:22px}
    .octa-page:has(.meeting-reference-page){background:#05090c!important}.octa-page:has(.meeting-reference-page) .octa-main{padding:0 24px 0 28px!important}.octa-page:has(.meeting-reference-page) .octa-topbar{min-height:82px!important;padding:8px 4px 6px 10px!important;background:transparent!important;backdrop-filter:none!important}.octa-page:has(.meeting-reference-page) .octa-toplink{color:rgba(255,255,255,.88)!important}.octa-page:has(.meeting-reference-page) .octa-toplink.is-active:after,.octa-page:has(.meeting-reference-page) .octa-toplink.is-active:before{background:#fff!important}.octa-page:has(.meeting-reference-page) .octa-search{background:rgba(255,255,255,.055)!important;color:#fff!important;border:1px solid rgba(255,255,255,.08)!important;backdrop-filter:blur(22px)!important}.octa-page:has(.meeting-reference-page) .octa-search input{color:#fff!important}.octa-page:has(.meeting-reference-page) .octa-search input::placeholder{color:rgba(255,255,255,.58)!important}.octa-page:has(.meeting-reference-page) .octa-wordmark,.octa-page:has(.meeting-reference-page) .octa-notification-button{color:#fff!important}.meeting-reference-topbar{display:none!important}.meeting-reference-workspace{grid-template-rows:minmax(0,1fr) 82px!important}
    .meeting-slide-card{background:linear-gradient(145deg,rgba(35,39,41,.54),rgba(9,13,15,.68))!important;backdrop-filter:blur(28px) saturate(118%)!important}.meeting-slide-thumb{flex:0 0 58%!important;height:auto!important;aspect-ratio:16/9!important;border-radius:14px!important}.meeting-slide-thumb span{left:10px!important;bottom:13px!important;font-size:10px!important;max-width:74%!important}.meeting-slide-thumb small{right:8px!important;bottom:7px!important;font-size:7px!important}
    .presentation-live-shell{background:rgba(5,7,8,.82)!important;backdrop-filter:blur(30px) saturate(110%)!important;-webkit-backdrop-filter:blur(30px) saturate(110%)!important;isolation:isolate}.presentation-live-stage{width:100%!important;padding:34px 42px 96px!important;background:radial-gradient(circle at 50% 44%,rgba(255,255,255,.055),transparent 46%),rgba(5,7,8,.36)!important}.presentation-live-stage:before{content:"";position:absolute;inset:0;z-index:0;background:linear-gradient(135deg,rgba(255,255,255,.025),rgba(0,0,0,.18));backdrop-filter:blur(18px)}.presentation-live-image{position:relative!important;z-index:2!important;width:min(92vw,1920px)!important;height:auto!important;max-height:min(82vh,1080px)!important;aspect-ratio:16/9!important;object-fit:contain!important;border:1px solid rgba(255,255,255,.15)!important;border-radius:22px!important;background:rgba(7,8,9,.72)!important;box-shadow:0 40px 120px rgba(0,0,0,.58)!important}
    .presentation-live-shell>aside{position:fixed!important;right:24px!important;bottom:92px!important;top:auto!important;width:auto!important;max-width:none!important;height:auto!important;padding:0!important;border:0!important;background:transparent!important;z-index:2147483350!important}.presentation-live-shell>aside>div:first-child{display:none!important}.presentation-live-shell>aside>.space-y-2{display:flex!important;gap:10px!important}.presentation-live-shell>aside>.space-y-2>div{position:relative!important;width:108px!important;height:192px!important;aspect-ratio:9/16!important;overflow:hidden!important;padding:0!important;border:1px solid rgba(255,255,255,.16)!important;border-radius:18px!important;background:rgba(8,9,10,.72)!important;box-shadow:0 18px 50px rgba(0,0,0,.42)!important}.presentation-live-shell>aside>.space-y-2>div:nth-child(n+3){display:none!important}.presentation-live-shell>aside>.space-y-2>div>img{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;border-radius:0!important;object-fit:cover!important}.presentation-live-shell>aside>.space-y-2>div>div{position:absolute!important;z-index:2!important;left:9px!important;right:9px!important;bottom:10px!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important;text-shadow:0 2px 10px rgba(0,0,0,.8)!important}.presentation-live-shell>aside>.space-y-2>div:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,transparent 56%,rgba(0,0,0,.82));pointer-events:none}.octa-pips-compact .presentation-live-shell>aside>.space-y-2>div{width:72px!important;height:128px!important;border-radius:14px!important}.octa-pips-compact .presentation-live-shell>aside{right:18px!important;bottom:90px!important}
    .octa-pip-compact-toggle{position:fixed;right:24px;bottom:52px;height:34px;display:flex;align-items:center;gap:7px;padding:0 11px;border:1px solid rgba(255,255,255,.14);border-radius:17px;background:rgba(10,11,12,.76);color:#fff;font-size:9px;backdrop-filter:blur(20px)}.octa-slide-paused{position:fixed;left:50%;bottom:34px;transform:translateX(-50%);width:min(560px,calc(100vw - 40px));display:flex;align-items:center;gap:18px;padding:14px 16px;border:1px solid rgba(255,255,255,.16);border-radius:22px;background:rgba(14,16,17,.78);color:#fff;box-shadow:0 28px 80px rgba(0,0,0,.4);backdrop-filter:blur(30px)}.octa-slide-paused>div{min-width:0;flex:1}.octa-slide-paused small,.octa-slide-paused b,.octa-slide-paused span{display:block}.octa-slide-paused small{font-size:8px;letter-spacing:.14em;color:rgba(255,255,255,.43)}.octa-slide-paused b{margin-top:4px;font-size:12px}.octa-slide-paused span{margin-top:4px;font-size:9px;color:rgba(255,255,255,.52)}.octa-slide-paused button{display:flex;align-items:center;gap:7px;white-space:nowrap;border:0;border-radius:14px;background:#fff;color:#111;padding:10px 13px;font-size:10px;font-weight:650}.octa-presentation-paused .presentation-live-shell{background:transparent!important;backdrop-filter:none!important;pointer-events:none!important}.octa-presentation-paused .presentation-live-shell .presentation-live-stage,.octa-presentation-paused .presentation-live-shell>aside{opacity:0!important;visibility:hidden!important}
    @media(min-width:1280px){.meeting-reference-grid{grid-template-columns:minmax(270px,.86fr) minmax(270px,.86fr) minmax(330px,1.08fr)!important}.meeting-host-zone{justify-items:center!important}.meeting-status-card{width:100%!important}.meeting-reference-host-card{height:100%!important;width:auto!important;max-width:100%!important;aspect-ratio:9/16!important}.meeting-reference-grid>.participant-stage{align-self:end!important;justify-self:center!important;height:calc(100% - 78px)!important;width:auto!important;max-width:100%!important;aspect-ratio:9/16!important}}
  `}</style>
 </aside><PresentationEscBridge/>{editing&&<ProfileEditor profile={profile} onClose={()=>setEditing(false)} onSaved={setProfile}/>}</>}
export function TopNav(){const path=usePathname();const router=useRouter();const[query,setQuery]=useState('');const[notificationsOpen,setNotificationsOpen]=useState(false);const runSearch=(e:React.FormEvent)=>{e.preventDefault();if(query.trim())router.push(`/reunioes?q=${encodeURIComponent(query.trim())}`)};const notifications=[{icon:CalendarDays,title:'Reunião em 30 minutos',text:'Planejamento de Marketing começa às 14:30.',time:'agora'},{icon:VideoIcon,title:'Gravação processada',text:'A gravação da última reunião já está disponível.',time:'há 8 min'},{icon:Sparkles,title:'Skills atualizou',text:'Seu desempenho semanal subiu 6,4%.',time:'há 22 min'}];return <header className="octa-topbar"><OctaLogo/><nav className="hidden items-center gap-8 lg:flex">{topItems.map(({href,label})=><Link key={label} href={href} className={`octa-toplink ${path===href?'is-active':''}`}>{label}</Link>)}</nav><div className="ml-auto flex min-w-0 items-center gap-4"><form onSubmit={runSearch} className="octa-search hidden min-w-[340px] xl:flex"><Search size={21}/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Buscar" placeholder="Buscar reunião, pessoa ou gravação"/></form><div className="octa-notification-wrap"><button type="button" className="octa-notification-button" aria-label="Notificações" aria-expanded={notificationsOpen} onClick={()=>setNotificationsOpen(open=>!open)}><Bell size={22}/><span className="octa-notification-badge">3</span></button>{notificationsOpen&&<div className="octa-notification-panel"><header><strong>Notificações</strong><span>3 novas</span></header>{notifications.map(({icon:Icon,title,text,time})=><div key={title} className="octa-notification-item"><span className="octa-notification-icon"><Icon size={16}/></span><div><b>{title}</b><p>{text}</p><small>{time}</small></div></div>)}</div>}</div><Link href="/profile" className="grid size-10 place-items-center rounded-full bg-white/70 text-black lg:hidden"><CircleUserRound size={18}/></Link></div></header>}
export function MobileNav(){const path=usePathname();return <nav className="fixed bottom-4 left-1/2 z-50 flex -translate-x-1/2 gap-1 rounded-full border border-black/10 bg-white/90 p-1.5 shadow-xl backdrop-blur-2xl xl:hidden">{sidePrimary.slice(0,4).map(({href,label,icon:Icon})=><Link key={label} aria-label={label} href={href} className={`grid size-11 place-items-center rounded-full ${path===href?'bg-black text-white':'text-black/55'}`}><Icon size={18}/></Link>)}<Link href="/configuracoes" className="grid size-11 place-items-center rounded-full text-black/55"><Menu size={18}/></Link></nav>}
