'use client';
import { Check, ShieldCheck, Sparkles, X } from 'lucide-react';
import { videoFilterPresets } from '@/lib/video-filters';

export function VideoFilterPanel({selected,intensity,onSelect,onIntensity,onClose}:{selected:string;intensity:number;onSelect:(id:string)=>void;onIntensity:(value:number)=>void;onClose:()=>void}){
  const activeId=selected==='natural'?'auto-face':selected;
  return <div className="video-filter-panel !w-[440px] max-w-[calc(100vw-32px)] !rounded-[24px] !border-white/10 !bg-[linear-gradient(145deg,rgba(18,22,27,.98),rgba(10,13,17,.98))] !p-4 shadow-[0_30px_90px_rgba(0,0,0,.48)]" role="dialog" aria-label="Filtros inteligentes">
    <div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-white"><Sparkles size={17}/><h3 className="text-[17px] font-semibold">Filtros inteligentes</h3></div><p className="mt-1 text-[11px] text-white/48">Aprimore sua presença em vídeo sem deixar o rosto artificial.</p></div><button onClick={onClose} aria-label="Fechar filtros" className="grid size-9 place-items-center rounded-full bg-white/[.06] text-white/65 transition hover:bg-white/10"><X size={16}/></button></div>
    <div className="no-scrollbar mt-4 max-h-[410px] space-y-2 overflow-y-auto pr-1">{videoFilterPresets.map((p,index)=>{const active=activeId===p.id;return <button key={p.id} onClick={()=>onSelect(p.id==='auto-face'?'natural':p.id)} className={`flex w-full items-center gap-3 rounded-[16px] border px-3 py-2.5 text-left transition ${active?'border-violet-400/70 bg-violet-400/[.08]':'border-white/[.07] bg-white/[.035] hover:bg-white/[.065]'}`}><span className={`grid size-11 shrink-0 place-items-center rounded-[13px] border ${active?'border-violet-300/25 bg-violet-400/10 text-violet-200':'border-white/8 bg-white/[.045] text-white/55'}`}>{index===0?<Sparkles size={17}/>:<span className="text-[10px] font-semibold">{String(index).padStart(2,'0')}</span>}</span><span className="min-w-0 flex-1"><b className="block text-[12px] font-semibold text-white">{p.name}</b><small className="mt-0.5 block text-[9px] leading-4 text-white/45">{p.description}</small></span><span className={`grid size-5 shrink-0 place-items-center rounded-full border ${active?'border-cyan-300/50 bg-cyan-300/20 text-cyan-100':'border-white/30 text-transparent'}`}>{active&&<Check size={12}/>}</span></button>})}</div>
    <label className="mt-4 block text-[11px] text-white/55"><span className="flex items-center justify-between"><span>Intensidade do efeito</span><b className="font-medium text-white/85">{intensity}%</b></span><input className="mt-3 w-full accent-violet-400" type="range" min="0" max="100" value={intensity} onChange={e=>onIntensity(Number(e.target.value))}/></label>
    <div className="mt-4 flex items-start gap-2 rounded-[15px] border border-white/[.06] bg-white/[.025] px-3 py-3"><ShieldCheck size={15} className="mt-0.5 shrink-0 text-emerald-300/80"/><div><b className="block text-[10px] font-medium text-white/70">Processamento local</b><span className="mt-0.5 block text-[9px] leading-4 text-white/38">Os ajustes visuais são aplicados no seu navegador; o filtro não envia sua imagem para um servidor.</span></div></div>
  </div>;
}
