'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { Suspense, useMemo, useState } from 'react';
import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Plus, UsersRound, X } from 'lucide-react';
import { PageShell } from '@/components/page-shell';
import { demoMeetings, demoParticipants } from '@/lib/demo/data';
const months=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const invitees=demoParticipants.slice(0,6);const participantById=new Map(demoParticipants.map(person=>[person.id,person]));
function AgendaAvatars({ids}:{ids:string[]}){return <span className="agenda-avatar-stack">{ids.slice(0,4).map(id=>{const person=participantById.get(id);return person?.avatarUrl?<Image key={id} src={person.avatarUrl} alt={person.displayName} width={24} height={24} className="agenda-avatar"/>:null})}</span>}
function AgendaContent(){const search=useSearchParams();const[month,setMonth]=useState(7);const[selected,setSelected]=useState(29);const[showCreate,setShowCreate]=useState(search.get('new')==='1');const[created,setCreated]=useState<{title:string;date:string;time:string;participantIds:string[]}|null>(null);const[title,setTitle]=useState('');const[date,setDate]=useState('2026-08-29');const[time,setTime]=useState('14:30');const[selectedParticipants,setSelectedParticipants]=useState<string[]>([]);const monthLabel=useMemo(()=>`${months[month]} 2026`,[month]);const toggleParticipant=(id:string)=>setSelectedParticipants(ids=>ids.includes(id)?ids.filter(value=>value!==id):[...ids,id]);const save=()=>{if(!title.trim())return;setCreated({title:title.trim(),date,time,participantIds:selectedParticipants});setTitle('');setSelectedParticipants([]);setShowCreate(false)};
return <PageShell title="Agenda" kicker="Organize seu dia" actions={<button onClick={()=>setShowCreate(true)} className="octa-primary-button"><Plus size={15}/> Agendar reunião</button>}><div className="relative grid h-full grid-cols-[.72fr_1.28fr] gap-4">
<section className="octa-panel agenda-calendar-card p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">{monthLabel}</h2><div className="flex gap-2"><button onClick={()=>setMonth(m=>(m+11)%12)} className="octa-icon-button" aria-label="Mês anterior"><ChevronLeft size={17}/></button><button onClick={()=>setMonth(m=>(m+1)%12)} className="octa-icon-button" aria-label="Próximo mês"><ChevronRight size={17}/></button></div></div><div className="mt-5 grid grid-cols-7 gap-2 text-center text-xs text-white/45">{['D','S','T','Q','Q','S','S'].map((d,i)=><span key={`${d}-${i}`}>{d}</span>)}</div><div className="mt-2 grid grid-cols-7 gap-2">{Array.from({length:35},(_,i)=>{const day=i-2;const valid=day>0&&day<=31;return <button disabled={!valid} onClick={()=>valid&&setSelected(day)} key={i} className={`agenda-day aspect-square rounded-xl text-sm ${day===selected?'is-selected':valid?'':'text-transparent'}`}>{valid?day:''}</button>})}</div><div className="agenda-summary mt-5 rounded-[20px] p-4"><div className="text-xs text-white/55">Dia {selected}</div><div className="mt-1 text-xl font-medium">{created?'4':'3'} reuniões</div><div className="mt-3 flex items-center gap-2 text-xs text-white/65"><Clock3 size={14}/> 2h 35min reservados</div></div></section>
<section className="octa-panel agenda-calendar-card overflow-hidden p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">{selected} de {months[month].toLowerCase()}</h2><p className="text-sm text-white/45">Sua agenda selecionada</p></div><CalendarDays className="text-white/65"/></div><div className="mt-5 grid gap-3">{created&&<article className="agenda-black-card grid grid-cols-[74px_1fr_auto] items-center gap-4 rounded-[20px] p-4"><div className="text-sm font-medium">{created.time}</div><div><h3 className="font-semibold">{created.title}</h3><div className="mt-1 flex items-center gap-2 text-xs text-white/50"><AgendaAvatars ids={created.participantIds}/><span>{new Date(`${created.date}T12:00:00`).toLocaleDateString('pt-BR')} • {created.participantIds.length} participantes</span></div></div><Link href="/room/strategy-room" className="octa-secondary-button">Entrar</Link></article>}{demoMeetings.slice(0,3).map((m,i)=><article key={m.id} className="agenda-black-card grid grid-cols-[74px_1fr_auto] items-center gap-4 rounded-[20px] p-4"><div className="text-sm font-medium">{['10:30','14:30','17:30'][i]}</div><div><h3 className="font-semibold">{m.title}</h3><div className="mt-1 flex items-center gap-3 text-xs text-white/50"><AgendaAvatars ids={m.participantIds}/><span>{m.durationLabel}</span><span className="flex items-center gap-1"><UsersRound size={13}/>{m.participantIds.length} pessoas</span></div></div><Link href={`/room/${m.slug}`} className="octa-secondary-button">Entrar</Link></article>)}</div></section>
{showCreate&&<div className="absolute inset-0 z-20 grid place-items-center rounded-[28px] bg-black/55 p-5 backdrop-blur-sm"><div className="w-full max-w-[520px] rounded-[30px] border border-white/10 bg-[#090a0b] p-6 text-white shadow-2xl"><div className="flex items-center justify-between"><div><p className="octa-kicker">Nova reunião</p><h2 className="mt-1 text-2xl font-semibold">Agendar</h2></div><button onClick={()=>setShowCreate(false)} className="octa-icon-button" aria-label="Fechar"><X size={17}/></button></div><label className="mt-5 block text-xs font-medium text-white/55">Assunto<input value={title} onChange={e=>setTitle(e.target.value)} className="octa-input mt-2 w-full" placeholder="Ex.: Branding"/></label><div className="mt-4 grid grid-cols-2 gap-3"><label className="block text-xs font-medium text-white/55">Data<input value={date} onChange={e=>setDate(e.target.value)} type="date" className="octa-input mt-2 w-full"/></label><label className="block text-xs font-medium text-white/55">Horário<input value={time} onChange={e=>setTime(e.target.value)} type="time" className="octa-input mt-2 w-full"/></label></div><div className="mt-5"><div className="flex items-center justify-between"><span className="text-xs font-medium text-white/55">Adicionar participantes</span><span className="text-[10px] text-white/40">{selectedParticipants.length} selecionados</span></div><div className="mt-3 flex flex-wrap gap-3">{invitees.map(person=>{const active=selectedParticipants.includes(person.id);return <button type="button" key={person.id} onClick={()=>toggleParticipant(person.id)} className={`group relative flex w-[64px] flex-col items-center gap-1.5 rounded-2xl p-2 transition ${active?'bg-white/12 ring-1 ring-white/25':'hover:bg-white/6'}`}><span className="relative size-10 overflow-hidden rounded-full bg-white/10">{person.avatarUrl&&<Image src={person.avatarUrl} alt={person.displayName} fill className="object-cover"/>}{active&&<span className="absolute bottom-0 right-0 grid size-4 place-items-center rounded-full bg-white text-black"><Check size={10}/></span>}</span><span className="w-full truncate text-[9px] text-white/60">{person.displayName.split(' ')[0]}</span></button>})}</div></div><button onClick={save} disabled={!title.trim()} className="octa-primary-button mt-5 w-full disabled:opacity-40">Salvar reunião</button></div></div>}</div></PageShell>}
export default function AgendaPage(){return <Suspense fallback={null}><AgendaContent/></Suspense>}
