'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { Suspense,useMemo,useState } from 'react';
import { Bell,CalendarDays,Check,ChevronLeft,ChevronRight,Clock3,Plus,Search,UsersRound,X } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { demoMeetings,demoParticipants } from '@/lib/demo/data';
import { buildMonthGrid,shiftMonth,toDateKey } from '@/lib/br-calendar';

const BR_TIME_ZONE='America/Sao_Paulo';
const invitees=demoParticipants.slice(0,6);const participantById=new Map(demoParticipants.map(person=>[person.id,person]));
type CreatedMeeting={id:string;title:string;date:string;time:string;participantIds:string[]};
function AgendaAvatars({ids}:{ids:string[]}){return <span className="agenda-ref-avatars">{ids.slice(0,4).map(id=>{const person=participantById.get(id);return person?.avatarUrl?<Image key={id} src={person.avatarUrl} alt={person.displayName} width={26} height={26}/>:null})}</span>}
function brazilParts(value:Date|string){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:BR_TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(value));const get=(type:Intl.DateTimeFormatPartTypes)=>Number(parts.find(part=>part.type===type)?.value);return{year:get('year'),month:get('month'),day:get('day')}}
function brazilDateKey(value:Date|string){const{year,month,day}=brazilParts(value);return toDateKey(year,month-1,day)}
const capitalize=(v:string)=>v.charAt(0).toUpperCase()+v.slice(1);

function AgendaContent(){
 const search=useSearchParams();const now=useMemo(()=>new Date(),[]);const today=useMemo(()=>brazilParts(now),[now]);const initialKey=toDateKey(today.year,today.month-1,today.day);
 const[cursor,setCursor]=useState({year:today.year,month:today.month-1});const[selectedKey,setSelectedKey]=useState(initialKey);const[showCreate,setShowCreate]=useState(search.get('new')==='1');const[created,setCreated]=useState<CreatedMeeting[]>([]);const[title,setTitle]=useState('');const[date,setDate]=useState(initialKey);const[time,setTime]=useState('14:30');const[selectedParticipants,setSelectedParticipants]=useState<string[]>([]);
 const grid=useMemo(()=>buildMonthGrid(cursor.year,cursor.month),[cursor]);const monthLabel=useMemo(()=>capitalize(new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric',timeZone:BR_TIME_ZONE}).format(new Date(Date.UTC(cursor.year,cursor.month,1,12)))),[cursor]);const selectedDate=useMemo(()=>{const[y,m,d]=selectedKey.split('-').map(Number);return new Date(Date.UTC(y,m-1,d,12))},[selectedKey]);const dayLabel=new Intl.DateTimeFormat('pt-BR',{day:'numeric',month:'long',year:'numeric',timeZone:BR_TIME_ZONE}).format(selectedDate);const demoForDay=useMemo(()=>demoMeetings.filter(meeting=>brazilDateKey(meeting.scheduledAt)===selectedKey),[selectedKey]);const createdForDay=useMemo(()=>created.filter(meeting=>meeting.date===selectedKey),[created,selectedKey]);const totalMeetings=demoForDay.length+createdForDay.length;
 const moveMonth=(delta:number)=>setCursor(current=>shiftMonth(current.year,current.month,delta));const selectCell=(cell:(typeof grid)[number])=>{setSelectedKey(cell.key);if(!cell.currentMonth)setCursor({year:cell.date.getFullYear(),month:cell.date.getMonth()})};const openCreate=()=>{setDate(selectedKey);setShowCreate(true)};const toggleParticipant=(id:string)=>setSelectedParticipants(ids=>ids.includes(id)?ids.filter(value=>value!==id):[...ids,id]);const save=()=>{if(!title.trim())return;setCreated(items=>[...items,{id:`created-${Date.now()}`,title:title.trim(),date,time,participantIds:selectedParticipants}]);const[y,m]=date.split('-').map(Number);setSelectedKey(date);setCursor({year:y,month:m-1});setTitle('');setSelectedParticipants([]);setShowCreate(false)};
 return <AppShell showTopNav={false}><div className="agenda-reference-page">
   <Image src="/agenda-background.webp" alt="" fill priority className="agenda-reference-bg" sizes="100vw"/>
   <div className="agenda-reference-shade"/>
   <header className="agenda-reference-top"><form className="agenda-reference-search"><Search size={20}/><input aria-label="Buscar" placeholder="Buscar reunião, pessoa ou gravação"/></form><nav><Link href="/">Início</Link><Link href="/reunioes">Reuniões</Link><Link href="/agenda" className="active">Agenda</Link><Link href="/planos">Planos e preços</Link><button type="button" aria-label="Notificações"><Bell size={21}/></button></nav></header>
   <div className="agenda-reference-action"><button onClick={openCreate}><Plus size={18}/>Agendar reunião</button></div>
   <main className="agenda-reference-grid">
    <section className="agenda-reference-glass agenda-reference-calendar"><div className="agenda-reference-section-head"><h2>{monthLabel}</h2><div><button onClick={()=>moveMonth(-1)} aria-label="Mês anterior"><ChevronLeft/></button><button onClick={()=>moveMonth(1)} aria-label="Próximo mês"><ChevronRight/></button></div></div><div className="agenda-weekdays">{['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(day=><span key={day}>{day}</span>)}</div><div className="agenda-days">{grid.map(cell=><button key={cell.key} onClick={()=>selectCell(cell)} className={`${cell.key===selectedKey?'selected ':''}${cell.currentMonth?'':'outside'}`}>{cell.day}</button>)}</div><div className="agenda-day-summary"><span>{capitalize(dayLabel)}</span><strong>{totalMeetings} {totalMeetings===1?'reunião':'reuniões'}</strong><small><Clock3 size={15}/>{totalMeetings?`${totalMeetings} compromisso${totalMeetings===1?'':'s'} neste dia`:'Dia livre para agendar'}</small></div></section>
    <section className="agenda-reference-glass agenda-reference-day"><div className="agenda-reference-section-head agenda-reference-day-title"><div><h2>{capitalize(dayLabel)}</h2><p>Sua agenda selecionada</p></div><CalendarDays/></div><div className="agenda-reference-meetings">{createdForDay.map(meeting=><article key={meeting.id}><time>{meeting.time}</time><div><h3>{meeting.title}</h3><div className="agenda-ref-meta"><AgendaAvatars ids={meeting.participantIds}/><span>{meeting.participantIds.length} pessoas</span></div></div><Link href="/room/strategy-room">Entrar</Link></article>)}{demoForDay.map(meeting=><article key={meeting.id}><time>{new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',timeZone:BR_TIME_ZONE}).format(new Date(meeting.scheduledAt))}</time><div><h3>{meeting.title}</h3><div className="agenda-ref-meta"><AgendaAvatars ids={meeting.participantIds}/><span>{meeting.durationLabel}</span><span><UsersRound size={14}/>{meeting.participantIds.length} pessoas</span></div></div><Link href={`/room/${meeting.slug}`}>Entrar</Link></article>)}{!totalMeetings&&<div className="agenda-reference-empty"><CalendarDays/><b>Nenhuma reunião neste dia</b><button onClick={openCreate}>Agendar neste dia</button></div>}</div></section>
   </main>
   {showCreate&&<div className="agenda-reference-modal"><div><header><div><small>Nova reunião</small><h2>Agendar</h2></div><button onClick={()=>setShowCreate(false)} aria-label="Fechar"><X/></button></header><label>Assunto<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: Estratégia e Crescimento"/></label><section><label>Data<input value={date} onChange={e=>setDate(e.target.value)} type="date"/></label><label>Horário<input value={time} onChange={e=>setTime(e.target.value)} type="time"/></label></section><p>Adicionar participantes</p><div className="agenda-reference-invitees">{invitees.map(person=>{const active=selectedParticipants.includes(person.id);return <button type="button" key={person.id} onClick={()=>toggleParticipant(person.id)} className={active?'active':''}><span>{person.avatarUrl&&<Image src={person.avatarUrl} alt={person.displayName} fill/>}{active&&<i><Check size={10}/></i>}</span><small>{person.displayName.split(' ')[0]}</small></button>})}</div><button className="agenda-reference-save" onClick={save} disabled={!title.trim()}>Salvar reunião</button></div></div>}
   <style jsx global>{`
    .agenda-reference-page{position:relative;height:100dvh;overflow:hidden;background:#0d0f10;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","SF Pro Text",Inter,sans-serif}.agenda-reference-bg{object-fit:cover;object-position:center!important;z-index:0}.agenda-reference-shade{position:absolute;inset:0;z-index:1;background:linear-gradient(90deg,rgba(5,7,8,.55),rgba(8,9,10,.28) 44%,rgba(7,8,9,.42)),linear-gradient(180deg,rgba(5,6,7,.43),rgba(5,6,7,.08) 45%,rgba(6,7,8,.34));backdrop-filter:saturate(92%)}
    .agenda-reference-top{position:relative;z-index:3;height:92px;display:flex;align-items:center;justify-content:space-between;padding:18px 48px 8px 28px}.agenda-reference-search{width:392px;height:54px;border:1px solid rgba(255,255,255,.11);border-radius:30px;display:flex;align-items:center;gap:13px;padding:0 18px;background:rgba(54,56,57,.48);backdrop-filter:blur(28px) saturate(120%);box-shadow:inset 0 1px 0 rgba(255,255,255,.08)}.agenda-reference-search input{width:100%;border:0;outline:0;background:transparent;color:#fff;font-size:14px}.agenda-reference-search input::placeholder{color:rgba(255,255,255,.8)}.agenda-reference-top nav{display:flex;align-items:center;gap:46px;font-size:15px}.agenda-reference-top nav a{position:relative;color:rgba(255,255,255,.92)}.agenda-reference-top nav a.active::after{content:"";position:absolute;left:50%;bottom:-17px;width:6px;height:6px;border-radius:50%;background:#fff;transform:translateX(-50%)}.agenda-reference-top nav button{border:0;background:transparent;color:#fff;padding:8px}
    .agenda-reference-action{position:relative;z-index:3;height:66px;display:flex;align-items:center;justify-content:flex-end;padding:0 48px}.agenda-reference-action button{height:48px;padding:0 22px;border:1px solid rgba(255,255,255,.08);border-radius:17px;background:rgba(37,39,40,.55);color:#fff;display:flex;align-items:center;gap:12px;font-size:14px;backdrop-filter:blur(24px)}
    .agenda-reference-grid{position:relative;z-index:3;height:calc(100dvh - 158px);display:grid;grid-template-columns:420px minmax(0,1fr);gap:20px;padding:12px 46px 34px 24px}.agenda-reference-glass{border:1px solid rgba(255,255,255,.17);border-radius:24px;background:linear-gradient(145deg,rgba(45,45,44,.34),rgba(16,18,19,.26));backdrop-filter:blur(26px) saturate(115%);box-shadow:inset 0 1px 0 rgba(255,255,255,.06),0 28px 60px rgba(0,0,0,.12)}.agenda-reference-calendar{padding:22px 20px 20px}.agenda-reference-section-head{display:flex;align-items:center;justify-content:space-between}.agenda-reference-section-head h2{margin:0;font-size:19px;font-weight:520;letter-spacing:-.025em}.agenda-reference-section-head>div:last-child{display:flex;gap:10px}.agenda-reference-section-head button{width:42px;height:42px;border:0;border-radius:12px;background:rgba(255,255,255,.15);color:#fff;display:grid;place-items:center}.agenda-weekdays{display:grid;grid-template-columns:repeat(7,1fr);margin-top:24px;color:rgba(255,255,255,.75);font-size:12px;text-align:center}.agenda-days{display:grid;grid-template-columns:repeat(7,1fr);gap:8px;margin-top:8px}.agenda-days button{aspect-ratio:1;border:1px solid transparent;border-radius:12px;background:transparent;color:#fff;font-size:15px}.agenda-days button.outside{color:rgba(255,255,255,.45)}.agenda-days button.selected{border-color:rgba(255,255,255,.92);background:rgba(255,255,255,.09);box-shadow:inset 0 0 0 1px rgba(255,255,255,.16)}.agenda-day-summary{margin-top:18px;border:1px solid rgba(255,255,255,.12);border-radius:20px;padding:18px 17px;background:rgba(17,17,17,.24);display:flex;flex-direction:column}.agenda-day-summary span{font-size:12px;color:rgba(255,255,255,.72)}.agenda-day-summary strong{margin-top:8px;font-size:21px;font-weight:520}.agenda-day-summary small{margin-top:16px;display:flex;align-items:center;gap:8px;color:rgba(255,255,255,.76);font-size:11px}
    .agenda-reference-day{padding:22px 20px;overflow:hidden}.agenda-reference-day-title p{margin:7px 0 0;color:rgba(255,255,255,.65);font-size:13px}.agenda-reference-day-title>svg{color:#fff}.agenda-reference-meetings{display:grid;gap:12px;margin-top:28px}.agenda-reference-meetings article{min-height:116px;display:grid;grid-template-columns:78px minmax(0,1fr) auto;align-items:center;gap:16px;padding:16px 18px;border:1px solid rgba(255,255,255,.13);border-radius:22px;background:linear-gradient(100deg,rgba(23,23,23,.62),rgba(26,27,27,.37));backdrop-filter:blur(20px)}.agenda-reference-meetings time{font-size:16px}.agenda-reference-meetings h3{margin:0;font-size:18px;font-weight:520;letter-spacing:-.02em}.agenda-ref-meta{margin-top:9px;display:flex;align-items:center;gap:10px;color:rgba(255,255,255,.68);font-size:12px}.agenda-ref-meta>span:last-child{display:flex;align-items:center;gap:5px}.agenda-ref-avatars{display:flex;padding-left:7px}.agenda-ref-avatars img{width:26px!important;height:26px!important;border-radius:50%;object-fit:cover;border:2px solid rgba(14,15,16,.8);margin-left:-7px}.agenda-reference-meetings article>a{min-width:84px;height:48px;border:1px solid rgba(255,255,255,.16);border-radius:13px;display:grid;place-items:center;background:rgba(255,255,255,.045);font-size:14px}.agenda-reference-empty{min-height:180px;border:1px solid rgba(255,255,255,.11);border-radius:22px;display:grid;place-items:center;align-content:center;gap:12px;color:rgba(255,255,255,.75)}.agenda-reference-empty button{border:1px solid rgba(255,255,255,.15);border-radius:12px;background:rgba(255,255,255,.08);color:#fff;padding:10px 15px}
    .agenda-reference-modal{position:absolute;inset:0;z-index:20;display:grid;place-items:center;background:rgba(0,0,0,.42);backdrop-filter:blur(12px)}.agenda-reference-modal>div{width:min(520px,calc(100vw - 32px));border:1px solid rgba(255,255,255,.17);border-radius:28px;padding:24px;background:rgba(18,18,18,.72);backdrop-filter:blur(34px);box-shadow:0 35px 90px rgba(0,0,0,.4)}.agenda-reference-modal header{display:flex;justify-content:space-between}.agenda-reference-modal header small,.agenda-reference-modal p,.agenda-reference-modal label{color:rgba(255,255,255,.62);font-size:11px}.agenda-reference-modal h2{margin:4px 0 0;font-size:24px}.agenda-reference-modal header button{width:38px;height:38px;border:1px solid rgba(255,255,255,.1);border-radius:50%;background:rgba(255,255,255,.07);color:#fff}.agenda-reference-modal label{display:block;margin-top:17px}.agenda-reference-modal input{display:block;width:100%;height:44px;margin-top:7px;border:1px solid rgba(255,255,255,.12);border-radius:13px;background:rgba(255,255,255,.07);color:#fff;padding:0 13px;outline:0}.agenda-reference-modal section{display:grid;grid-template-columns:1fr 1fr;gap:12px}.agenda-reference-invitees{display:flex;gap:10px}.agenda-reference-invitees button{width:58px;border:0;background:transparent;color:#fff}.agenda-reference-invitees button>span{position:relative;display:block;width:42px;height:42px;margin:auto;border-radius:50%;overflow:hidden;background:rgba(255,255,255,.08)}.agenda-reference-invitees img{object-fit:cover}.agenda-reference-invitees i{position:absolute;right:0;bottom:0;width:15px;height:15px;border-radius:50%;display:grid;place-items:center;background:#fff;color:#111}.agenda-reference-invitees small{display:block;margin-top:5px;font-size:9px;color:rgba(255,255,255,.65)}.agenda-reference-save{width:100%;height:46px;margin-top:20px;border:1px solid rgba(255,255,255,.16);border-radius:13px;background:rgba(255,255,255,.16);color:#fff}.agenda-reference-save:disabled{opacity:.4}
    @media(max-width:1279px){.agenda-reference-top{padding:14px 18px}.agenda-reference-top nav{gap:20px}.agenda-reference-grid{grid-template-columns:minmax(320px,.8fr) 1.2fr;padding:10px 18px 100px}.agenda-reference-search{width:330px}}
    @media(max-width:860px){.agenda-reference-top nav a{display:none}.agenda-reference-search{width:min(70vw,360px)}.agenda-reference-action{padding:0 18px}.agenda-reference-grid{height:auto;overflow:auto;grid-template-columns:1fr;padding:10px 14px 110px}.agenda-reference-page{overflow:auto}.agenda-reference-calendar{min-height:610px}.agenda-reference-day{min-height:430px}.agenda-reference-meetings article{grid-template-columns:65px 1fr}.agenda-reference-meetings article>a{grid-column:2;justify-self:start;width:90px}}
   `}</style>
  </div></AppShell>
}
export default function AgendaPage(){return <Suspense fallback={null}><AgendaContent/></Suspense>}
