'use client';
import { useEffect,useMemo,useState } from 'react';
import { ArrowUp,ChevronDown,Loader2,Mic,MicOff,Sparkles,Volume2,X } from 'lucide-react';
import { OctaDigitalMark } from './octa-digital-mark';
import { useOctaRealtimeVoice } from './use-octa-realtime-voice';
import { aggregateSkillAnalyses,overallScore } from '@/lib/skills-analysis';
import { ANALYSIS_UPDATED_EVENT,listMeetingAnalyses } from '@/lib/meeting-analysis-store';
import { currentUser } from '@/lib/demo/data';

type ChatMessage={role:'assistant'|'user';text:string;actions?:string[]};
type OpenCoachEvent=CustomEvent<{question?:string}>;
type ProfileUpdatedEvent=CustomEvent<{name?:string}>;
const PROFILE_NAME_KEY='octa-profile-name';
const shortcuts=['O que devo melhorar?','Prepare minha próxima reunião','compare minhas últimas reuniões','me dê um treino prático'];

function welcome(profileName:string,meetingTitle?:string){return `Olá, ${profileName}. Sou a OCTA AI. ${meetingTitle?`Estou acompanhando o contexto de “${meetingTitle}”. `:''}Posso analisar suas reuniões, explicar sua evolução, preparar sua próxima conversa e transformar evidências em ações práticas.`}

export function OctaSkillCoach({meetingTitle}:{meetingTitle?:string}){
 const[open,setOpen]=useState(false);const[input,setInput]=useState('');const[loading,setLoading]=useState(false);const[version,setVersion]=useState(0);const[profileName,setProfileName]=useState(currentUser.displayName);const[messages,setMessages]=useState<ChatMessage[]>([{role:'assistant',text:welcome(currentUser.displayName,meetingTitle)}]);const voice=useOctaRealtimeVoice();
 useEffect(()=>{let savedName=currentUser.displayName;try{savedName=localStorage.getItem(PROFILE_NAME_KEY)||currentUser.displayName}catch{}setProfileName(savedName);setMessages(m=>m.length===1&&m[0].role==='assistant'?[{role:'assistant',text:welcome(savedName,meetingTitle)}]:m);const sync=()=>setVersion(v=>v+1);const openCoach=(event:Event)=>{const detail=(event as OpenCoachEvent).detail;setOpen(true);if(detail?.question)setInput(detail.question)};const profileUpdated=(event:Event)=>{const detail=(event as ProfileUpdatedEvent).detail;const next=detail?.name?.trim()||currentUser.displayName;setProfileName(next);setMessages(m=>m.length===1&&m[0].role==='assistant'?[{role:'assistant',text:welcome(next,meetingTitle)}]:m)};window.addEventListener(ANALYSIS_UPDATED_EVENT,sync);window.addEventListener('storage',sync);window.addEventListener('octa-ai:open',openCoach);window.addEventListener('octa-profile:updated',profileUpdated);return()=>{window.removeEventListener(ANALYSIS_UPDATED_EVENT,sync);window.removeEventListener('storage',sync);window.removeEventListener('octa-ai:open',openCoach);window.removeEventListener('octa-profile:updated',profileUpdated)}},[meetingTitle]);
 const context=useMemo(()=>{void version;const analyses=listMeetingAnalyses().filter(a=>a.source==='ai');const skills=aggregateSkillAnalyses(analyses);return{profileName,overallScore:overallScore(skills),skills,recent:analyses.slice(0,8).map(a=>({meetingTitle:a.meetingTitle,summary:a.summary,overallScore:a.overallScore??null}))}},[version,profileName]);
 async function send(preset?:string){const question=(preset??input).trim();if(!question||loading)return;setMessages(m=>[...m,{role:'user',text:question}]);setInput('');setLoading(true);try{const performanceQuestion=meetingTitle?`Reunião atual: ${meetingTitle}. ${question}`:question;const response=await fetch('/api/ai/skills-coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:performanceQuestion,context})});const data=await response.json();if(!response.ok){setMessages(m=>[...m,{role:'assistant',text:data.message||'Não consegui consultar a IA agora.'}]);return}setMessages(m=>[...m,{role:'assistant',text:data.answer,actions:data.actions}])}catch{setMessages(m=>[...m,{role:'assistant',text:'A conexão com a OCTA AI falhou. O chat continua disponível e suas análises permanecem salvas.'}])}finally{setLoading(false)}}
 function listenMessage(text:string){if(typeof window==='undefined'||!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='pt-BR';utterance.rate=.98;utterance.pitch=1.02;const voices=window.speechSynthesis.getVoices();const pt=voices.filter(v=>v.lang.toLowerCase().startsWith('pt-br'));utterance.voice=pt.find(v=>/female|feminina|maria|luciana|camila|francisca|google português/i.test(v.name))||pt[0]||voices.find(v=>v.lang.toLowerCase().startsWith('pt'))||null;window.speechSynthesis.speak(utterance)}
 function close(){voice.stop();if(typeof window!=='undefined'&&'speechSynthesis' in window)window.speechSynthesis.cancel();setOpen(false)}
 return <div className={`octa-ai-coach ${open?'is-open':''}`}>
   {open&&<section className="octa-ai-panel" aria-label="OCTA AI"><header><div className="octa-ai-reference-title"><OctaDigitalMark size={38}/><div><b>OCTA AI</b><span>Inteligência privada para suas reuniões</span></div></div><button onClick={close} aria-label="Fechar OCTA AI"><X size={17}/></button></header><div className="octa-ai-scoreline"><Sparkles size={14}/><span>{context.overallScore===null?`${profileName}, pronta para ajudar com sua próxima reunião`:`${profileName} · Performance ${context.overallScore}/100`}</span></div><div className="octa-ai-messages">{messages.map((m,i)=><div key={i} className={`octa-ai-message ${m.role}`}><p>{m.text}</p>{m.role==='assistant'&&<button className="octa-ai-message-listen" type="button" onClick={()=>listenMessage(m.text)} aria-label="Ouvir resposta"><Volume2 size={13}/><span>Ouvir resposta</span></button>}{m.actions?.length?<div className="octa-ai-actions">{m.actions.map(a=><button type="button" key={a} onClick={()=>send(a)}>{a}</button>)}</div>:null}</div>)}{loading&&<div className="octa-ai-thinking"><Loader2 size={15} className="animate-spin"/> analisando contexto...</div>}</div><div className="octa-ai-shortcuts">{shortcuts.map(item=><button key={item} onClick={()=>send(item)}>{item}</button>)}</div>{voice.state!=='idle'&&<div className={`octa-ai-voice-state is-${voice.state}`}><Volume2 size={13}/><span>{voice.state==='connecting'?'Conectando voz...':voice.state==='speaking'?'OCTA AI falando...':voice.state==='listening'?'OCTA AI ouvindo...':voice.error}</span></div>}<form className="octa-ai-reference-composer" onSubmit={e=>{e.preventDefault();send()}}><OctaDigitalMark size={28}/><input value={input} onChange={e=>setInput(e.target.value)} placeholder={`Fale comigo, ${profileName}...`}/><button type="button" className={`octa-ai-voice-button ${voice.active?'is-active':''}`} onClick={()=>voice.active?voice.stop():void voice.start()} aria-label={voice.active?'Desligar voz da OCTA AI':'Falar com a OCTA AI'}>{voice.active?<MicOff size={17}/>:<Mic size={17}/>}</button><button disabled={!input.trim()||loading} aria-label="Enviar"><ArrowUp size={17}/></button></form><footer>Privado · respostas conectadas às evidências disponíveis nas suas reuniões.</footer></section>}
   <button className="octa-ai-orb" onClick={()=>open?close():setOpen(true)} aria-label={open?'Minimizar OCTA AI':'Abrir OCTA AI'}><OctaDigitalMark size={34}/><span>OCTA AI</span>{open&&<ChevronDown size={13}/>}</button>
 </div>
}
