'use client';
import { useEffect,useMemo,useRef,useState } from 'react';
import { ArrowUp,ChevronDown,Loader2,Mic,MicOff,Sparkles,Volume2,X } from 'lucide-react';
import { OctaDigitalMark } from './octa-digital-mark';
import { useOctaRealtimeVoice } from './use-octa-realtime-voice';
import { aggregateSkillAnalyses,overallScore } from '@/lib/skills-analysis';
import { ANALYSIS_UPDATED_EVENT,listMeetingAnalyses } from '@/lib/meeting-analysis-store';
import { isNearChatBottom } from '@/lib/chat-auto-scroll';
type ChatMessage={role:'assistant'|'user';text:string;actions?:string[]};type OpenCoachEvent=CustomEvent<{question?:string}>;type ProfileUpdatedEvent=CustomEvent<{name?:string}>;
const shortcuts=['Como vender melhor?','Prepare minha próxima reunião','Melhore meu pitch','O que devo melhorar?'];
function welcome(profileName:string,meetingTitle?:string){const hello=profileName?`Olá, ${profileName}.`:'Olá.';return `${hello} Sou a OCTA AI. ${meetingTitle?`Estou com o contexto de “${meetingTitle}”. `:''}Pode perguntar sobre negócios, vendas, comunicação, aprendizado, estratégia, vida prática ou qualquer outro assunto. Quando houver dados das suas reuniões e Skills, uso esse contexto para personalizar a resposta.`}
function replaceProfileName(text:string,previousName:string,nextName:string){if(!previousName||previousName===nextName)return text;return text.replace(new RegExp(previousName.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'gi'),nextName)}
export function OctaSkillCoach({meetingTitle}:{meetingTitle?:string}){
 const[open,setOpen]=useState(false);const[input,setInput]=useState('');const[loading,setLoading]=useState(false);const[version,setVersion]=useState(0);const[profileName,setProfileName]=useState('');const[messages,setMessages]=useState<ChatMessage[]>([]);const voice=useOctaRealtimeVoice();const messagesRef=useRef<HTMLDivElement|null>(null);const autoScrollRef=useRef(true);const previousProfileNameRef=useRef('');
 const scrollToLatest=(behavior:ScrollBehavior='smooth')=>{const el=messagesRef.current;if(!el)return;el.scrollTo({top:el.scrollHeight,behavior})};
 useEffect(()=>{let active=true;const applyOfficialProfile=(next:string)=>{const clean=next.trim();if(!active)return;const previous=previousProfileNameRef.current;previousProfileNameRef.current=clean;setProfileName(clean);setMessages(current=>{if(current.length===0)return[{role:'assistant',text:welcome(clean,meetingTitle)}];return current.map((message,index)=>index===0&&message.role==='assistant'?{...message,text:welcome(clean,meetingTitle)}:{...message,text:replaceProfileName(message.text,previous,clean)})})};fetch('/api/profile',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(data=>applyOfficialProfile(data?.profile?.displayName||'')).catch(()=>applyOfficialProfile(''));const sync=()=>setVersion(v=>v+1);const openCoach=(event:Event)=>{const detail=(event as OpenCoachEvent).detail;setOpen(true);autoScrollRef.current=true;if(detail?.question)setInput(detail.question)};const profileUpdated=(event:Event)=>{const detail=(event as ProfileUpdatedEvent).detail;const eventName=detail?.name?.trim();if(eventName)applyOfficialProfile(eventName);else fetch('/api/profile',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(data=>applyOfficialProfile(data?.profile?.displayName||'')).catch(()=>{})};window.addEventListener(ANALYSIS_UPDATED_EVENT,sync);window.addEventListener('octa-ai:open',openCoach);window.addEventListener('octa-profile:updated',profileUpdated);return()=>{active=false;window.removeEventListener(ANALYSIS_UPDATED_EVENT,sync);window.removeEventListener('octa-ai:open',openCoach);window.removeEventListener('octa-profile:updated',profileUpdated)}},[meetingTitle]);
 useEffect(()=>{if(open&&autoScrollRef.current)requestAnimationFrame(()=>scrollToLatest('smooth'))},[open,messages,loading]);
 const context=useMemo(()=>{void version;const analyses=listMeetingAnalyses().filter(a=>a.source==='ai');const skills=aggregateSkillAnalyses(analyses);return{profileName:profileName||undefined,overallScore:overallScore(skills),skills,recent:analyses.slice(0,8).map((a,index)=>({meetingTitle:a.meetingTitle,summary:a.summary,overallScore:a.overallScore??null,transcript:index<3&&a.transcript?a.transcript.slice(0,6000):undefined}))}},[version,profileName]);
 async function send(preset?:string){const question=(preset??input).trim();if(!question||loading)return;const history=messages.slice(-16).map(({role,text})=>({role,text}));autoScrollRef.current=true;setMessages(m=>[...m,{role:'user',text:question}]);setInput('');setLoading(true);requestAnimationFrame(()=>scrollToLatest('smooth'));try{const currentQuestion=meetingTitle?`Contexto da reunião atual: ${meetingTitle}. Pergunta do usuário: ${question}`:question;const response=await fetch('/api/ai/skills-coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:currentQuestion,history,context})});const data=await response.json();if(!response.ok){setMessages(m=>[...m,{role:'assistant',text:data.message||'A OCTA AI está temporariamente indisponível.'}]);return}setMessages(m=>[...m,{role:'assistant',text:data.answer,actions:data.actions}])}catch{setMessages(m=>[...m,{role:'assistant',text:'A conexão com a OCTA AI falhou agora. Tente novamente em instantes.'}])}finally{setLoading(false)}}
 function listenMessage(text:string){if(typeof window==='undefined'||!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='pt-BR';utterance.rate=.98;utterance.pitch=1.02;const voices=window.speechSynthesis.getVoices();const pt=voices.filter(v=>v.lang.toLowerCase().startsWith('pt-br'));utterance.voice=pt.find(v=>/female|feminina|maria|luciana|camila|francisca|google português/i.test(v.name))||pt[0]||voices.find(v=>v.lang.toLowerCase().startsWith('pt'))||null;window.speechSynthesis.speak(utterance)}
 function close(){voice.stop();if(typeof window!=='undefined'&&'speechSynthesis' in window)window.speechSynthesis.cancel();setOpen(false)}const person=profileName||'Você';
 return <div className={`octa-ai-coach ${open?'is-open':''}`}>{open&&<section className="octa-ai-panel" aria-label="OCTA AI"><header><div className="octa-ai-reference-title"><OctaDigitalMark size={38}/><div><b>OCTA AI</b><span>Inteligência para negócios, aprendizado e reuniões</span></div></div><button onClick={close} aria-label="Fechar OCTA AI"><X size={17}/></button></header><div className="octa-ai-scoreline"><Sparkles size={14}/><span>{context.overallScore===null?`${person}, pronta para responder e ajudar`:`${person} · Performance ${context.overallScore}/100`}</span></div><div ref={messagesRef} onScroll={()=>{const el=messagesRef.current;if(el)autoScrollRef.current=isNearChatBottom(el)}} className="octa-ai-messages">{messages.map((m,i)=><div key={i} className={`octa-ai-message ${m.role}`}><p>{m.text}</p>{m.role==='assistant'&&<button className="octa-ai-message-listen" type="button" onClick={()=>listenMessage(m.text)} aria-label="Ouvir resposta"><Volume2 size={13}/><span>Ouvir resposta</span></button>}{m.actions?.length?<div className="octa-ai-actions">{m.actions.map(a=><button type="button" key={a} onClick={()=>send(a)}>{a}</button>)}</div>:null}</div>)}{loading&&<div className="octa-ai-thinking"><Loader2 size={15} className="animate-spin"/> pensando...</div>}</div><div className="octa-ai-shortcuts">{shortcuts.map(item=><button key={item} onClick={()=>send(item)}>{item}</button>)}</div>{voice.state!=='idle'&&<div className={`octa-ai-voice-state is-${voice.state}`}><Volume2 size={13}/><span>{voice.state==='connecting'?'Conectando voz...':voice.state==='speaking'?'OCTA AI falando...':voice.state==='listening'?'OCTA AI ouvindo...':voice.error}</span></div>}<form className="octa-ai-reference-composer" onSubmit={e=>{e.preventDefault();send()}}><OctaDigitalMark size={28}/><input value={input} onChange={e=>setInput(e.target.value)} placeholder={profileName?`Pergunte qualquer coisa, ${profileName}...`:'Pergunte qualquer coisa...'}/><button type="button" className={`octa-ai-voice-button ${voice.active?'is-active':''}`} onClick={()=>voice.active?voice.stop():void voice.start()} aria-label={voice.active?'Desligar voz da OCTA AI':'Falar com a OCTA AI'}>{voice.active?<MicOff size={17}/>:<Mic size={17}/>}</button><button disabled={!input.trim()||loading} aria-label="Enviar"><ArrowUp size={17}/></button></form><footer>IA geral com contexto das suas reuniões e Skills quando disponível.</footer></section>}<button className="octa-ai-orb" onClick={()=>{if(open)close();else{autoScrollRef.current=true;setOpen(true)}}} aria-label={open?'Minimizar OCTA AI':'Abrir OCTA AI'}><OctaDigitalMark size={34}/><span>OCTA AI</span>{open&&<ChevronDown size={13}/>}</button></div>
}
