export type AIProviderFailure='not_configured'|'provider_error'|'rate_limited'|'quota_exhausted';
export function isGenerativeAIEnabled(){if(process.env.OCTA_AI_MODE==='disabled')return false;return Boolean(process.env.OPENAI_API_KEY||process.env.AI_GATEWAY_API_KEY||process.env.VERCEL_OIDC_TOKEN)}
export function classifyProviderError(status:number,detail:string):AIProviderFailure{if(status!==429)return'provider_error';const lower=detail.toLowerCase();if(lower.includes('insufficient_quota')||lower.includes('quota')||lower.includes('billing')||lower.includes('credit'))return'quota_exhausted';return'rate_limited'}
function retryDelay(response:Response,attempt:number){const raw=response.headers.get('retry-after');if(raw){const seconds=Number(raw);if(Number.isFinite(seconds))return Math.min(5000,Math.max(250,seconds*1000))}return Math.min(4000,600*Math.pow(2,attempt))}
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
export async function runOpenAIJson<T>(instructions:string,input:string):Promise<{ok:true;data:T}|{ok:false;reason:AIProviderFailure;message:string}>{
 if(!isGenerativeAIEnabled())return{ok:false,reason:'not_configured',message:'A IA generativa não está configurada no ambiente.'};
 const openAIKey=process.env.OPENAI_API_KEY;const gatewayKey=process.env.AI_GATEWAY_API_KEY||process.env.VERCEL_OIDC_TOKEN;const useGateway=!openAIKey&&Boolean(gatewayKey);const key=openAIKey||gatewayKey;if(!key)return{ok:false,reason:'not_configured',message:'A IA generativa não está configurada no ambiente.'};
 const endpoint=useGateway?'https://ai-gateway.vercel.sh/v1/responses':'https://api.openai.com/v1/responses';const configuredModel=process.env.OPENAI_MODEL||'gpt-5.6-luna';const model=useGateway&&!configuredModel.includes('/')?`openai/${configuredModel}`:configuredModel;
 for(let attempt=0;attempt<3;attempt++){try{const response=await fetch(endpoint,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,instructions,input:`Responda SOMENTE com JSON válido, sem markdown.\n${input}`,reasoning:{effort:'low'},...(useGateway?{providerOptions:{gateway:{disallowPromptTraining:true}}}:{})})});if(!response.ok){const detail=await response.text().catch(()=>'');const reason=classifyProviderError(response.status,detail);console.error('OCTA AI provider error',response.status,detail.slice(0,500));if(reason==='quota_exhausted')return{ok:false,reason,message:'A cota do provedor de IA foi atingida.'};const transient=reason==='rate_limited'||response.status>=500;if(transient&&attempt<2){await sleep(retryDelay(response,attempt));continue}return{ok:false,reason,message:reason==='rate_limited'?'O provedor está limitando requisições agora. Tente novamente em instantes.':`Falha no provedor de IA (${response.status}).`}}const payload=await response.json();const text=payload.output_text??payload.output?.flatMap((item:any)=>item.content??[]).find((c:any)=>c.type==='output_text')?.text;if(!text)return{ok:false,reason:'provider_error',message:'A IA não retornou conteúdo utilizável.'};return{ok:true,data:JSON.parse(text) as T}}catch(error){console.error('OCTA AI request error',error);if(attempt<2){await sleep(600*Math.pow(2,attempt));continue}return{ok:false,reason:'provider_error',message:'Não foi possível concluir a chamada ao provedor.'}}}return{ok:false,reason:'provider_error',message:'Não foi possível concluir a chamada ao provedor.'}}
