'use client';
import Image from 'next/image';
import { Camera, Check, Sparkles } from 'lucide-react';
import { useState } from 'react';
import { PageShell } from '@/components/page-shell';
import { Button, Card, Pill } from '@/components/ui';
import { currentUser } from '@/lib/demo/data';

export default function ProfilePage(){
 const [name,setName]=useState(currentUser.displayName); const [headline,setHeadline]=useState(currentUser.headline??''); const [company,setCompany]=useState(currentUser.company??''); const [saved,setSaved]=useState(false);
 return <PageShell title="Perfil" kicker="Sua presença antes da câmera ligar"><section className="octa-profile-page"><div className="apple-shell rounded-[38px] p-6 md:rounded-[46px] md:p-10"><Pill><Sparkles size={13}/> Perfil instantâneo</Pill><h1 className="mt-5 max-w-4xl text-5xl font-medium leading-[.92] tracking-[-.06em] md:text-7xl">Sua presença,<br/><span className="text-black/25">antes da câmera ligar.</span></h1></div>
 <Card className="mt-5 grid gap-6 p-4 md:grid-cols-[360px_1fr] md:p-5"><div className="relative mx-auto aspect-[4/5] w-full overflow-hidden rounded-[30px] bg-black">{currentUser.avatarUrl&&<Image src={currentUser.avatarUrl} alt={name} fill className="object-cover grayscale-[15%]"/>}<div className="absolute inset-0 bg-gradient-to-t from-black/45 via-transparent to-transparent"/><div className="absolute bottom-5 left-5 text-white"><div className="text-2xl font-semibold tracking-[-.035em]">{name}</div><div className="mt-1 text-xs text-white/55">{headline}</div></div><button className="absolute right-4 top-4 grid size-11 place-items-center rounded-full bg-white text-black shadow-lg"><Camera size={17}/></button></div><div className="flex flex-col justify-center p-2 md:p-6"><div className="max-w-xl space-y-5"><Field label="Nome" value={name} onChange={setName}/><Field label="Título / atuação" value={headline} onChange={setHeadline}/><Field label="Empresa" value={company} onChange={setCompany}/><div><label className="text-[10px] font-semibold uppercase tracking-[.16em] text-black/35">Status</label><div className="mt-2 flex gap-2"><button className="rounded-full bg-black px-4 py-2.5 text-sm text-white">● Disponível</button><button className="rounded-full border border-black/10 bg-white px-4 py-2.5 text-sm text-black/45">Em reunião</button></div></div><Button onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),1600)}} className="flex items-center gap-2">{saved?<><Check size={16}/> Salvo</>:<>Salvar alterações</>}</Button></div></div></Card>
 </section></PageShell>
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="text-[10px] font-semibold uppercase tracking-[.16em] text-black/35">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-[20px] border border-black/[.08] bg-white px-4 py-4 text-[15px] outline-none transition focus:border-black/25 focus:shadow-[0_0_0_4px_rgba(0,0,0,.035)]"/></label>}
