'use client';
import { GripHorizontal, Maximize2, MonitorUp, Pause, Play, Square, X } from 'lucide-react';
import { ReactNode, useEffect, useRef, useState } from 'react';

export function FloatingToolCard({title,subtitle,icon,onClose,children,initialX=320,initialY=110,width=320}:{title:string;subtitle?:string;icon:ReactNode;onClose:()=>void;children:ReactNode;initialX?:number;initialY?:number;width?:number}){
  const panel=useRef<HTMLDivElement>(null);const drag=useRef<{x:number;y:number;left:number;top:number}|null>(null);const [position,setPosition]=useState({x:initialX,y:initialY});
  useEffect(()=>{const move=(e:PointerEvent)=>{if(!drag.current||!panel.current)return;const rect=panel.current.getBoundingClientRect();setPosition({x:Math.max(8,Math.min(window.innerWidth-rect.width-8,drag.current.left+e.clientX-drag.current.x)),y:Math.max(8,Math.min(window.innerHeight-rect.height-8,drag.current.top+e.clientY-drag.current.y))})};const up=()=>drag.current=null;window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)}},[]);
  return <div ref={panel} style={{left:position.x,top:position.y,width}} className="fixed z-[86] rounded-[24px] border border-white/10 bg-[#09131d]/94 p-4 text-white shadow-[0_28px_90px_rgba(0,0,0,.55)] backdrop-blur-2xl">
    <div className="flex cursor-grab items-center gap-2 active:cursor-grabbing" onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY,left:position.x,top:position.y}}}><GripHorizontal size={15} className="text-white/35"/><span className="grid size-9 place-items-center rounded-xl bg-cyan-300/10 text-cyan-200">{icon}</span><div className="min-w-0 flex-1"><b className="block truncate text-sm">{title}</b>{subtitle&&<span className="mt-0.5 block truncate text-[10px] text-white/38">{subtitle}</span>}</div><button onClick={onClose} className="grid size-8 place-items-center rounded-full hover:bg-white/8" aria-label={`Ocultar ${title}`}><X size={15}/></button></div>
    <div className="mt-4">{children}</div>
  </div>;
}

export function ShareScreenCard({active,onToggle,onHide}:{active:boolean;onToggle:()=>void;onHide:()=>void}){return <FloatingToolCard title="Compartilhar tela" subtitle={active?'Visível para os participantes':'Escolha o que deseja compartilhar'} icon={<MonitorUp size={17}/>} onClose={onHide} initialX={360} initialY={118}><div className={`rounded-[18px] border p-3 ${active?'border-cyan-300/25 bg-cyan-300/8':'border-white/8 bg-white/[.035]'}`}><p className="text-xs leading-5 text-white/60">{active?'Sua tela está sendo transmitida na reunião. Você pode ocultar este card sem interromper o compartilhamento.':'Ao iniciar, o navegador perguntará qual tela, janela ou aba você quer mostrar aos participantes.'}</p><button onClick={onToggle} className={`mt-3 flex h-10 w-full items-center justify-center gap-2 rounded-xl text-xs font-semibold ${active?'bg-rose-500/15 text-rose-200':'bg-white text-[#0a2238]'}`}>{active?<><Square size={14}/>Encerrar compartilhamento</>:<><MonitorUp size={14}/>Compartilhar agora</>}</button></div></FloatingToolCard>}

export function ScreenRecordingCard({onHide}:{onHide:()=>void}){
  const [recording,setRecording]=useState(false);const [paused,setPaused]=useState(false);const [elapsed,setElapsed]=useState(0);const recorder=useRef<MediaRecorder|null>(null);const stream=useRef<MediaStream|null>(null);const chunks=useRef<Blob[]>([]);
  useEffect(()=>{if(!recording)return;const id=window.setInterval(()=>setElapsed(v=>v+1),1000);return()=>window.clearInterval(id)},[recording]);
  useEffect(()=>()=>stream.current?.getTracks().forEach(t=>t.stop()),[]);
  const start=async()=>{try{const next=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});stream.current=next;chunks.current=[];const r=new MediaRecorder(next);recorder.current=r;r.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);r.onstop=()=>{const blob=new Blob(chunks.current,{type:r.mimeType||'video/webm'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`octa-gravacao-${Date.now()}.webm`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setRecording(false);setPaused(false)};r.start();setElapsed(0);setRecording(true);next.getVideoTracks()[0]?.addEventListener('ended',()=>r.state!=='inactive'&&r.stop())}catch{}};
  const stop=()=>{if(recorder.current&&recorder.current.state!=='inactive')recorder.current.stop()};const pause=()=>{const r=recorder.current;if(!r)return;if(r.state==='recording'){r.pause();setPaused(true)}else if(r.state==='paused'){r.resume();setPaused(false)}};
  const time=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`;
  return <FloatingToolCard title="Gravar tela" subtitle={recording?`${paused?'Pausada':'Gravando'} · ${time}`:'Gravação local no dispositivo'} icon={<span className={`size-3 rounded-full ${recording?'bg-rose-400 shadow-[0_0_12px_#fb7185]':'bg-white/45'}`}/>} onClose={onHide} initialX={720} initialY={118} width={300}><div className="rounded-[18px] border border-white/8 bg-white/[.035] p-3"><p className="text-xs leading-5 text-white/60">A gravação fica no seu dispositivo. Ao encerrar, o arquivo é baixado automaticamente.</p><div className="mt-3 flex gap-2">{!recording?<button onClick={start} className="flex h-10 flex-1 items-center justify-center gap-2 rounded-xl bg-white text-xs font-semibold text-[#0a2238]"><Play size={14}/>Iniciar</button>:<><button onClick={pause} className="grid size-10 place-items-center rounded-xl bg-white/8 text-white/70">{paused?<Play size={14}/>:<Pause size={14}/>}</button><button onClick={stop} className="flex h-10 flex-1 items-center justify-center gap-2 rounded-xl bg-rose-500/15 text-xs font-semibold text-rose-200"><Square size={13}/>Encerrar</button></>}</div></div></FloatingToolCard>}
