'use client';
import { useEffect, useMemo, useState } from 'react';
import {
  Camera, CameraOff, ChevronDown, Copy, Filter, Heart, MessageCircle, Mic, MicOff, MoreHorizontal, PhoneOff,
  ScreenShare, Send, Sparkles, SquarePen, UserPlus, UsersRound, Volume2, WandSparkles, CircleDot
} from 'lucide-react';
import { currentUser, demoMessages } from '@/lib/demo/data';
import { getProfile, PROFILE_UPDATED_EVENT } from '@/lib/profile-store';
import { DashboardSidebar } from '@/components/nav';
import { ToolOverlayProvider } from '@/components/tool-overlay-context';
import { ToolOverlay } from '@/components/tool-overlay';
import { ShareScreenCard, ScreenRecordingCard } from './floating-call-tool-card';
import { ChatOverlay } from '@/features/chat/chat-overlay';
import { WhiteboardPanel } from '@/features/whiteboard/whiteboard-panel';
import { MeetingDraggableFilter } from '@/components/meeting-draggable-filter';
import { NotesPanel } from '@/features/notes/notes-panel';
import { LiveKitStage } from './livekit-stage';
import { isLiveKitConfigured } from '@/lib/livekit/config';
import { filterCss } from '@/lib/video-filters';

export function InstantMeetingClient({slug,title}:{slug:string;title:string}){
  const [profile,setProfile]=useState(()=>getProfile());
  useEffect(()=>{const sync=()=>setProfile(getProfile());sync();window.addEventListener(PROFILE_UPDATED_EVENT,sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener(PROFILE_UPDATED_EVENT,sync);window.removeEventListener('storage',sync)}},[]);
  const host=useMemo(()=>({...currentUser,displayName:profile.displayName,headline:profile.headline,avatarUrl:profile.avatarUrl}),[profile]);
  const people=useMemo(()=>[host],[host]);
  const [chat,setChat]=useState(true);const [notes,setNotes]=useState(false);const [board,setBoard]=useState(false);const [filters,setFilters]=useState(false);
  const [shareCard,setShareCard]=useState(false);const [screenSharing,setScreenSharing]=useState(false);const [recordCard,setRecordCard]=useState(false);const [sidebarCollapsed,setSidebarCollapsed]=useState(false);
  const [mic,setMic]=useState(true);const [camera,setCamera]=useState(true);const [participantsOpen,setParticipantsOpen]=useState(true);const [mutedAll,setMutedAll]=useState(false);
  const [filter,setFilter]=useState('natural');const [intensity,setIntensity]=useState(80);const [toast,setToast]=useState('');
  const flash=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),1700)};
  const copyLink=async()=>{const url=typeof window==='undefined'?'':window.location.href;try{await navigator.clipboard.writeText(url);flash('Link copiado')}catch{flash('Copie o link da barra do navegador')}};
  const share=async()=>{const url=window.location.href;try{if(navigator.share)await navigator.share({title,url});else await navigator.clipboard.writeText(url);flash('Link pronto para compartilhar')}catch{}};
  const muteAll=()=>setMutedAll(x=>!x);
  return <ToolOverlayProvider><main className="relative h-[100dvh] overflow-hidden bg-[#020812] p-4 text-white">
    <div className="flex h-full min-w-0 gap-4"><DashboardSidebar collapsed={sidebarCollapsed} onToggle={()=>setSidebarCollapsed(v=>!v)}/>
      <section className="relative flex min-w-0 flex-1 flex-col overflow-hidden bg-[radial-gradient(circle_at_50%_35%,rgba(14,110,171,.13),transparent_34%)] px-4 py-4 lg:px-6">
        <header className="flex items-center justify-between gap-4"><div className="flex items-center gap-3 rounded-[22px] border border-white/10 bg-white/[.025] px-4 py-2.5"><span className="size-2.5 rounded-full bg-emerald-300 shadow-[0_0_16px_#38f5c4]"/><div><div className="text-sm font-medium">{title}</div><div className="mt-0.5 text-[10px] uppercase tracking-[.16em] text-emerald-300">AO VIVO <span className="ml-2 text-white/35">· 9:16</span></div></div><ChevronDown size={15} className="text-white/45"/></div><div className="flex items-center gap-2"><button onClick={copyLink} className="flex h-10 items-center gap-2 rounded-full border border-white/10 bg-white/[.03] px-4 text-xs text-white/80"><Copy size={14}/> Copiar link</button><button className="grid size-10 place-items-center rounded-full border border-white/10 bg-white/[.03]"><MoreHorizontal size={17}/></button></div></header>
        <div className="no-scrollbar mt-3 grid min-h-0 flex-1 grid-cols-[minmax(0,1fr)] gap-4 overflow-y-auto 2xl:grid-cols-[minmax(0,1fr)_360px]">
          <div className="flex min-h-0 flex-col items-center justify-center">
            <div className="relative w-full max-w-[390px] overflow-hidden rounded-[32px] border border-white/10 bg-[#07121d] shadow-[0_30px_90px_rgba(0,0,0,.46)]" style={{aspectRatio:'9/16'}}>
              <div className="absolute inset-0" style={{filter:filterCss(filter,intensity)}}>{isLiveKitConfigured?<LiveKitStage room={slug} identity={currentUser.id} name={profile.displayName} screenShare={screenSharing} onScreenShareError={message=>{setScreenSharing(false);flash(message)}}/>:<div className="absolute inset-0 grid place-items-center bg-[radial-gradient(circle_at_50%_35%,rgba(20,126,151,.18),transparent_34%),linear-gradient(180deg,#07131f,#020811)]"><div className="text-center"><div className="mx-auto grid size-20 place-items-center rounded-full border border-white/10 bg-white/[.035] text-2xl font-medium text-cyan-100">{profile.displayName.split(' ').map(part=>part[0]).slice(0,2).join('').toUpperCase()}</div><div className="mt-5 text-sm font-medium text-white/85">{camera?'Sua câmera aparecerá aqui':'Câmera desligada'}</div><div className="mt-2 text-[10px] text-white/38">Aguardando conexão da chamada</div></div></div>}</div>
              <div className="absolute left-4 top-4 z-10 flex items-center gap-2 rounded-full border border-white/10 bg-black/35 px-3 py-2 backdrop-blur-xl"><span className="grid size-8 place-items-center rounded-full bg-white/[.08] text-[10px] font-semibold text-cyan-100">{profile.displayName.split(' ').map(part=>part[0]).slice(0,2).join('').toUpperCase()}</span><div><div className="text-[11px] font-semibold">{profile.displayName}</div><div className="text-[9px] text-white/45">Você · anfitrião</div></div></div>
              <div className="absolute right-4 top-4 z-10 flex flex-col gap-2"><span className="rounded-full border border-white/10 bg-black/35 px-3 py-1.5 text-[10px] backdrop-blur-xl">9:16</span><span className="grid size-9 place-items-center rounded-full border border-white/10 bg-black/35 backdrop-blur-xl"><Volume2 size={14}/></span></div>
              <div className="absolute right-[-66px] top-1/2 z-20 hidden -translate-y-1/2 flex-col gap-3 lg:flex"><button className="flex size-11 flex-col items-center justify-center rounded-full border border-white/10 bg-[#06101a] text-white/80"><Heart size={17}/></button><button onClick={()=>setChat(true)} className="flex size-11 flex-col items-center justify-center rounded-full border border-white/10 bg-[#06101a] text-white/80"><MessageCircle size={17}/></button><button onClick={share} className="grid size-11 place-items-center rounded-full border border-white/10 bg-[#06101a] text-white/80"><Send size={17}/></button></div>
              {chat&&<ChatOverlay initialMessages={demoMessages} onClose={()=>setChat(false)}/>} 
            </div>
            <div className="mt-3 flex w-full max-w-[590px] items-center gap-2 rounded-[18px] border border-white/[.06] bg-white/[.025] p-2"><div className="flex items-center gap-2 rounded-[14px] border border-cyan-300/30 bg-cyan-300/[.06] px-3 py-2"><span className="grid size-9 place-items-center rounded-[11px] bg-white/[.06] text-[10px] font-semibold text-cyan-100">{profile.displayName.split(' ').map(part=>part[0]).slice(0,2).join('').toUpperCase()}</span><div><b className="block text-[11px] font-medium">{profile.displayName}</b><span className="text-[9px] text-white/38">Você iniciou a reunião</span></div></div><span className="ml-auto px-3 text-[10px] text-white/35">Aguardando participantes</span></div>
            <div className="mt-3 flex w-full max-w-[900px] items-center justify-center gap-1 rounded-[24px] border border-white/[.07] bg-white/[.03] p-2 backdrop-blur-xl">
              <Control label="Microfone" active={mic} onClick={()=>setMic(x=>!x)} icon={mic?<Mic size={18}/>:<MicOff size={18}/>}/><Control label="Câmera" active={camera} onClick={()=>setCamera(x=>!x)} icon={camera?<Camera size={18}/>:<CameraOff size={18}/>}/><Control label="Chat" onClick={()=>setChat(x=>!x)} icon={<MessageCircle size={18}/>}/><Control label="Anotar" onClick={()=>setNotes(true)} icon={<SquarePen size={18}/>}/><Control label="Participantes" onClick={()=>setParticipantsOpen(x=>!x)} icon={<UsersRound size={18}/>}/><Control label="Filtros" onClick={()=>setFilters(true)} icon={<Filter size={18}/>}/><Control label="Lousa" onClick={()=>setBoard(true)} icon={<WandSparkles size={18}/>}/><Control label="Compartilhar" active={!screenSharing} onClick={()=>setShareCard(true)} icon={<ScreenShare size={18}/>}/><Control label="Gravar tela" onClick={()=>setRecordCard(true)} icon={<CircleDot size={18}/>}/><button className="ml-2 flex h-12 items-center gap-2 rounded-full bg-[#ff4359] px-5 text-xs font-semibold" onClick={()=>window.location.href='/'}><PhoneOff size={17}/> Sair</button>
            </div>
          </div>
          {participantsOpen&&<aside className="hidden min-h-0 flex-col gap-4 2xl:flex"><section className="flex min-h-0 flex-1 flex-col rounded-[28px] border border-white/[.07] bg-white/[.035] p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.18em] text-white/35">Controles do anfitrião</p><h3 className="mt-2 text-base font-medium">Participantes</h3><p className="mt-1 text-xs text-white/40">{people.length} pessoa na reunião</p></div><UserPlus size={18} className="text-white/45"/></div><div className="no-scrollbar mt-4 flex-1 space-y-2 overflow-y-auto">{people.map(p=><div key={p.id} className="flex w-full items-center gap-3 rounded-[18px] border border-white/[.04] bg-black/10 p-2.5 text-left"><span className="grid size-11 shrink-0 place-items-center rounded-[13px] bg-white/[.055] text-[10px] font-semibold text-cyan-100">{p.displayName.split(' ').map(part=>part[0]).slice(0,2).join('').toUpperCase()}</span><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{p.displayName}</div><div className="mt-1 text-[10px] text-white/38">{p.role==='host'?'Anfitrião':'Participante'} · {p.canSpeak&&!mutedAll?'Pode falar':'Aguardando'}</div></div><span className={`h-5 w-1 rounded-full ${p.canSpeak&&!mutedAll?'bg-emerald-300':'bg-white/15'}`}/><MoreHorizontal size={15} className="text-white/35"/></div>)}</div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>flash('Convite pronto para compartilhar')} className="flex h-11 items-center justify-center gap-2 rounded-[15px] bg-white/[.055] text-xs"><UsersRound size={15}/> Convidar</button><button onClick={muteAll} className="flex h-11 items-center justify-center gap-2 rounded-[15px] bg-white/[.055] text-xs"><MicOff size={15}/>{mutedAll?'Liberar falas':'Silenciar todos'}</button></div></section><button onClick={()=>flash('Insights serão gerados durante a reunião')} className="flex h-[92px] items-center gap-3 rounded-[24px] border border-cyan-400/25 bg-[linear-gradient(135deg,rgba(8,94,130,.32),rgba(6,22,34,.75))] px-4 text-left"><span className="grid size-11 place-items-center rounded-full border border-cyan-300/30 text-cyan-300"><Sparkles size={19}/></span><span className="flex-1"><b className="block text-sm">Resumo rápido</b><span className="mt-1 block text-[10px] text-white/45">Aguardando conversa</span></span><ChevronDown size={16} className="-rotate-90 text-white/55"/></button></aside>}
        </div>
      </section>
    </div>
    {notes&&<NotesPanel roomSlug={slug} meetingTitle={title} onClose={()=>setNotes(false)}/>} {filters&&<MeetingDraggableFilter selected={filter} intensity={intensity} onSelect={setFilter} onIntensity={setIntensity} onClose={()=>setFilters(false)}/>} {board&&<WhiteboardPanel onClose={()=>setBoard(false)}/>}
    {shareCard&&<ShareScreenCard active={screenSharing} onToggle={()=>setScreenSharing(v=>!v)} onHide={()=>setShareCard(false)}/>} {recordCard&&<ScreenRecordingCard onHide={()=>setRecordCard(false)}/>}
    {toast&&<div className="fixed left-1/2 top-5 z-[90] -translate-x-1/2 rounded-full border border-white/10 bg-[#09131d]/90 px-4 py-2 text-xs shadow-2xl backdrop-blur-xl">{toast}</div>}
    <ToolOverlay/>
  </main></ToolOverlayProvider>;
}

function Control({label,icon,active=true,onClick}:{label:string;icon:React.ReactNode;active?:boolean;onClick?:()=>void}){
  return <button onClick={onClick} className={`flex min-w-[70px] flex-col items-center justify-center gap-1 rounded-[16px] px-2 py-2 text-[9px] transition ${active?'text-white/76 hover:bg-white/[.055]':'bg-rose-500/10 text-rose-300'}`}><span className="grid size-7 place-items-center">{icon}</span><span className="hidden lg:block">{label}</span></button>;
}
