'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  Camera, CameraOff, ChevronDown, Copy, Filter, MessageCircle, MessageCircleOff, Mic, MicOff, MoreHorizontal, PhoneOff,
  ScreenShare, Sparkles, SquarePen, UserPlus, UsersRound, WandSparkles, CircleDot, Play, RotateCcw, Pin
} from 'lucide-react';
import { currentUser, demoMessages, demoParticipants } from '@/lib/demo/data';
import { getProfile, PROFILE_UPDATED_EVENT } from '@/lib/profile-store';
import { DashboardSidebar } from '@/components/nav';
import { ToolOverlayProvider } from '@/components/tool-overlay-context';
import { ToolOverlay } from '@/components/tool-overlay';
import { ShareScreenCard, ScreenRecordingCard } from './floating-call-tool-card';
import { ChatOverlay } from '@/features/chat/chat-overlay';
import { WhiteboardPanel } from '@/features/whiteboard/whiteboard-panel';
import { MeetingDraggableFilter } from '@/components/meeting-draggable-filter';
import { NotesPanel } from '@/features/notes/notes-panel';
import { LiveKitStage } from './livekit-stage';
import { CameraPreview } from './camera-preview';
import { InviteParticipantsCard } from './invite-participants-card';
import { isLiveKitConfigured } from '@/lib/livekit/config';

type MeetingPhase='setup'|'live'|'ended';
const initials=(name:string)=>name.split(' ').map(part=>part[0]).slice(0,2).join('').toUpperCase();

export function InstantMeetingClient({slug,title}:{slug:string;title:string}){
  const [profile,setProfile]=useState(()=>getProfile());
  useEffect(()=>{const sync=()=>setProfile(getProfile());sync();window.addEventListener(PROFILE_UPDATED_EVENT,sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener(PROFILE_UPDATED_EVENT,sync);window.removeEventListener('storage',sync)}},[]);
  const [phase,setPhase]=useState<MeetingPhase>('setup');
  const [chat,setChat]=useState(false),[chatEnabled,setChatEnabled]=useState(true),[notes,setNotes]=useState(false),[board,setBoard]=useState(false),[whiteboardVisibleToParticipants,setWhiteboardVisibleToParticipants]=useState(false),[filters,setFilters]=useState(false),[inviteOpen,setInviteOpen]=useState(false);
  const [shareCard,setShareCard]=useState(false),[screenSharing,setScreenSharing]=useState(false),[recordCard,setRecordCard]=useState(false),[sidebarCollapsed,setSidebarCollapsed]=useState(false);
  const [mic,setMic]=useState(true),[camera,setCamera]=useState(true),[participantsOpen,setParticipantsOpen]=useState(true),[mutedAll,setMutedAll]=useState(false);
  const [filter,setFilter]=useState('natural'),[intensity,setIntensity]=useState(72),[toast,setToast]=useState(''),[processedTrack,setProcessedTrack]=useState<MediaStreamTrack|null>(null),[roomNames,setRoomNames]=useState<string[]>([]);
  const [spotlightName,setSpotlightName]=useState(profile.displayName);
  useEffect(()=>{setSpotlightName(current=>current===currentUser.displayName?profile.displayName:current)},[profile.displayName]);
  const onTrack=useCallback((track:MediaStreamTrack|null)=>setProcessedTrack(track),[]);
  const onParticipants=useCallback((names:string[])=>setRoomNames(names),[]);
  const meetingUrl=typeof window==='undefined'?'/reuniao-instantanea':window.location.href;
  const phaseLabel=phase==='setup'?'PRÉ-CALL':phase==='live'?'AO VIVO':'PÓS-CALL';
  const remoteNames=useMemo(()=>roomNames.filter(name=>name&&name!==profile.displayName),[roomNames,profile.displayName]);
  const participantNames=useMemo(()=>[profile.displayName,...remoteNames],[profile.displayName,remoteNames]);
  const avatarFor=(name:string)=>name===profile.displayName?profile.avatarUrl:demoParticipants.find(p=>p.displayName===name)?.avatarUrl;
  const selectedAvatar=avatarFor(spotlightName);
  const flash=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),1800)};
  const copyLink=async()=>{try{await navigator.clipboard.writeText(meetingUrl);flash('Link copiado')}catch{flash('Copie o link da barra do navegador')}};
  const endMeeting=()=>{setScreenSharing(false);setChat(false);setBoard(false);setPhase('ended');flash('Reunião encerrada · câmera disponível para teste')};
  const toggleChatEnabled=()=>setChatEnabled(value=>{const next=!value;if(!next)setChat(false);flash(next?'Chat liberado para os participantes':'Chat desativado pelo anfitrião');return next});
  const openChat=()=>{if(!chatEnabled){flash('Chat desativado pelo anfitrião');return}setChat(value=>!value)};

  const hostStage=<div className="relative h-full min-h-[520px] overflow-hidden rounded-[34px] border border-white/10 bg-[#07121d] shadow-[0_30px_90px_rgba(0,0,0,.42)]">
    {phase==='live'&&isLiveKitConfigured?<><CameraPreview enabled={camera} filterId={filter} intensity={intensity} onProcessedTrack={onTrack} className="absolute size-px opacity-0 pointer-events-none"/><LiveKitStage room={slug} identity={currentUser.id} name={profile.displayName} screenShare={screenSharing} cameraEnabled={camera} microphoneEnabled={mic} processedTrack={processedTrack} selectedName={spotlightName} fallbackName={spotlightName} fallbackAvatarUrl={selectedAvatar} chatEnabled={chatEnabled} whiteboardVisible={whiteboardVisibleToParticipants} onParticipantsChange={onParticipants} onRemoteControls={controls=>{if(typeof controls.chatEnabled==='boolean'){setChatEnabled(controls.chatEnabled);if(!controls.chatEnabled)setChat(false)}if(typeof controls.whiteboardVisible==='boolean')setWhiteboardVisibleToParticipants(controls.whiteboardVisible)}} onScreenShareError={message=>{setScreenSharing(false);flash(message)}}/></>:spotlightName===profile.displayName?<>{camera?<CameraPreview enabled filterId={filter} intensity={intensity} onProcessedTrack={onTrack} className="absolute inset-0"/>:<PausedProfile name={profile.displayName} avatarUrl={profile.avatarUrl}/>}</>:<PausedProfile name={spotlightName} avatarUrl={selectedAvatar}/>} 
    <div className="absolute left-4 top-4 z-10 flex items-center gap-2 rounded-full border border-white/10 bg-black/40 px-3 py-2 backdrop-blur-xl"><span className="grid size-8 place-items-center rounded-full bg-white/[.08] text-[10px] font-semibold text-cyan-100">{initials(spotlightName)}</span><div><div className="text-[11px] font-semibold">{spotlightName}</div><div className="text-[9px] text-white/45">{spotlightName===profile.displayName?'Anfitrião':'Em destaque'}</div></div></div>
    {phase==='live'&&chat&&chatEnabled&&<ChatOverlay initialMessages={demoMessages} onClose={()=>setChat(false)}/>} 
  </div>;

  return <ToolOverlayProvider><main className="relative h-[100dvh] overflow-hidden bg-[#020812] p-4 text-white"><div className="flex h-full min-w-0 gap-4"><DashboardSidebar collapsed={sidebarCollapsed} onToggle={()=>setSidebarCollapsed(v=>!v)}/><section className="relative flex min-w-0 flex-1 flex-col overflow-hidden bg-[radial-gradient(circle_at_50%_35%,rgba(14,110,171,.13),transparent_34%)] px-4 py-4 lg:px-6">
    <header className="flex items-center justify-between gap-4"><div className="flex items-center gap-3 rounded-[22px] border border-white/10 bg-white/[.025] px-4 py-2.5"><span className={`size-2.5 rounded-full ${phase==='live'?'bg-emerald-300 shadow-[0_0_16px_#38f5c4]':'bg-cyan-300/70'}`}/><div><div className="text-sm font-medium">{title}</div><div className="mt-0.5 text-[10px] uppercase tracking-[.16em] text-cyan-300">{phaseLabel} <span className="ml-2 text-white/35">· câmera 9:16</span></div></div><ChevronDown size={15} className="text-white/45"/></div><div className="flex items-center gap-2"><button onClick={()=>setInviteOpen(true)} className="flex h-10 items-center gap-2 rounded-full border border-cyan-300/18 bg-cyan-300/[.06] px-4 text-xs text-cyan-100"><UserPlus size={14}/> Adicionar participantes</button><button onClick={copyLink} className="flex h-10 items-center gap-2 rounded-full border border-white/10 bg-white/[.03] px-4 text-xs text-white/80"><Copy size={14}/> Copiar link</button><button className="grid size-10 place-items-center rounded-full border border-white/10 bg-white/[.03]"><MoreHorizontal size={17}/></button></div></header>

    {phase==='live'?<div className={`mt-3 grid min-h-0 flex-1 gap-3 overflow-hidden ${board?'2xl:grid-cols-[minmax(300px,.76fr)_minmax(430px,1.12fr)_minmax(330px,.88fr)]':'2xl:grid-cols-[minmax(380px,.95fr)_minmax(420px,1.05fr)]'}`}>
      <div className="min-h-0">{hostStage}</div>
      {board&&<div className="min-h-0 overflow-hidden rounded-[30px]"><WhiteboardPanel mode="inline" visibleToParticipants={whiteboardVisibleToParticipants} onVisibleToParticipantsChange={setWhiteboardVisibleToParticipants} onClose={()=>setBoard(false)}/></div>}
      <aside className="participant-wall min-h-0 overflow-hidden rounded-[30px] border border-white/[.07] bg-white/[.025] p-3"><div className="flex items-center justify-between gap-2 px-1 pb-3"><div><p className="text-[10px] uppercase tracking-[.16em] text-white/35">Participantes</p><h3 className="mt-1 text-sm font-semibold">Escolha quem fica em destaque</h3></div><div className="flex items-center gap-2"><button onClick={toggleChatEnabled} className={`flex h-9 items-center gap-2 rounded-full border px-3 text-[10px] ${chatEnabled?'border-cyan-300/25 bg-cyan-300/8 text-cyan-100':'border-white/10 bg-white/[.03] text-white/40'}`}>{chatEnabled?<MessageCircle size={13}/>:<MessageCircleOff size={13}/>} Chat {chatEnabled?'ativo':'desativado'}</button><button onClick={()=>setInviteOpen(true)} className="grid size-9 place-items-center rounded-full border border-white/10 bg-white/[.04] text-white/65"><UserPlus size={15}/></button></div></div><div className="no-scrollbar grid h-[calc(100%-48px)] grid-cols-2 gap-2 overflow-y-auto pr-1">{participantNames.map((name,index)=><ParticipantTile key={name} name={name} avatarUrl={avatarFor(name)} host={name===profile.displayName} selected={spotlightName===name} paused={name===profile.displayName?!camera:false} index={index} onClick={()=>setSpotlightName(name)}/>)}</div></aside>
    </div>:<div className="mt-3 flex min-h-0 flex-1 items-center justify-center"><div className="w-full max-w-[430px]" style={{aspectRatio:'9/16'}}>{hostStage}</div></div>}

    <div className="mt-3 flex w-full items-center justify-center gap-1 rounded-[24px] border border-white/[.07] bg-white/[.03] p-2 backdrop-blur-xl"><Control label="Microfone" active={mic} onClick={()=>setMic(x=>!x)} icon={mic?<Mic size={18}/>:<MicOff size={18}/>}/><Control label="Câmera" active={camera} onClick={()=>setCamera(x=>!x)} icon={camera?<Camera size={18}/>:<CameraOff size={18}/>}/><Control label="Filtros" onClick={()=>setFilters(true)} icon={<Filter size={18}/>}/>{phase==='live'&&<><Control label="Chat" active={chatEnabled} onClick={openChat} icon={chatEnabled?<MessageCircle size={18}/>:<MessageCircleOff size={18}/>}/><Control label="Anotar" onClick={()=>setNotes(true)} icon={<SquarePen size={18}/>}/><Control label="Participantes" onClick={()=>setParticipantsOpen(x=>!x)} icon={<UsersRound size={18}/>}/><Control label="Lousa" active={board} onClick={()=>setBoard(x=>!x)} icon={<WandSparkles size={18}/>}/><Control label="Compartilhar" active={!screenSharing} onClick={()=>setShareCard(true)} icon={<ScreenShare size={18}/>}/><Control label="Gravar tela" onClick={()=>setRecordCard(true)} icon={<CircleDot size={18}/>}/></>}{phase==='setup'&&<button onClick={()=>{setPhase('live');setSpotlightName(profile.displayName)}} className="ml-2 flex h-12 items-center gap-2 rounded-full bg-white px-5 text-xs font-semibold text-[#07131e]"><Play size={16}/> Iniciar reunião</button>}{phase==='live'&&<button className="ml-2 flex h-12 items-center gap-2 rounded-full bg-[#ff4359] px-5 text-xs font-semibold" onClick={endMeeting}><PhoneOff size={17}/> Encerrar</button>}{phase==='ended'&&<button onClick={()=>setPhase('setup')} className="ml-2 flex h-12 items-center gap-2 rounded-full bg-white px-5 text-xs font-semibold text-[#07131e]"><RotateCcw size={15}/> Nova reunião</button>}</div>
  </section></div>
  {inviteOpen&&<InviteParticipantsCard meetingUrl={meetingUrl} meetingTitle={title} hostName={profile.displayName} onClose={()=>setInviteOpen(false)} onSent={flash}/>} {notes&&<NotesPanel roomSlug={slug} meetingTitle={title} onClose={()=>setNotes(false)}/>} {filters&&<MeetingDraggableFilter selected={filter} intensity={intensity} onSelect={setFilter} onIntensity={setIntensity} onClose={()=>setFilters(false)}/>} {shareCard&&<ShareScreenCard active={screenSharing} onToggle={()=>setScreenSharing(v=>!v)} onHide={()=>setShareCard(false)}/>} {recordCard&&<ScreenRecordingCard onHide={()=>setRecordCard(false)}/>} {toast&&<div className="fixed left-1/2 top-5 z-[280] -translate-x-1/2 rounded-full border border-white/10 bg-[#09131d]/95 px-4 py-2 text-xs shadow-2xl backdrop-blur-xl">{toast}</div>}<ToolOverlay/>
  </main></ToolOverlayProvider>;
}

function PausedProfile({name,avatarUrl}:{name:string;avatarUrl?:string}){return <div className="absolute inset-0 grid place-items-center overflow-hidden bg-[#07121d]">{avatarUrl?<img src={avatarUrl} alt={name} className="absolute inset-0 size-full object-cover"/>:null}<div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/15 to-black/20"/><div className="relative z-10 text-center"><div className="mx-auto grid size-20 place-items-center rounded-full border border-white/15 bg-black/25 text-xl font-semibold">{initials(name)}</div><p className="mt-4 text-xs text-white/75">Câmera pausada</p></div></div>}
function ParticipantTile({name,avatarUrl,host,selected,paused,index,onClick}:{name:string;avatarUrl?:string;host:boolean;selected:boolean;paused:boolean;index:number;onClick:()=>void}){return <button onClick={onClick} className={`relative min-h-[190px] overflow-hidden rounded-[24px] border text-left transition ${index%3===1?'row-span-2 min-h-[300px]':''} ${selected?'border-cyan-300/70 ring-2 ring-cyan-300/15':'border-white/8 hover:border-white/20'}`}>{avatarUrl?<img src={avatarUrl} alt={name} className={`absolute inset-0 size-full object-cover ${paused?'opacity-90':''}`}/>:<div className="absolute inset-0 grid place-items-center bg-[radial-gradient(circle_at_50%_30%,rgba(34,142,170,.18),transparent_40%),#0a1520] text-2xl text-white/65">{initials(name)}</div>}<div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/10 to-black/5"/><div className="absolute inset-x-0 bottom-0 p-3"><div className="flex items-end justify-between gap-2"><div><b className="block text-sm font-medium text-white">{name}</b><span className="mt-1 block text-[9px] text-white/50">{host?'Anfitrião':paused?'Câmera pausada':'Participante'}</span></div>{selected&&<span className="grid size-8 place-items-center rounded-full bg-white text-[#07131e]"><Pin size={13}/></span>}</div></div></button>}
function Control({label,icon,active=true,onClick}:{label:string;icon:React.ReactNode;active?:boolean;onClick?:()=>void}){return <button onClick={onClick} className={`flex min-w-[70px] flex-col items-center justify-center gap-1 rounded-[16px] px-2 py-2 text-[9px] transition ${active?'text-white/76 hover:bg-white/[.055]':'bg-rose-500/10 text-rose-300'}`}><span className="grid size-7 place-items-center">{icon}</span><span className="hidden lg:block">{label}</span></button>}
