'use client';
import { FormEvent, useState } from 'react';
import { Check, Mail, MessageCircle, Send, UsersRound, X } from 'lucide-react';
import { demoParticipants } from '@/lib/demo/data';

export function InviteParticipantsCard({meetingUrl,meetingTitle,hostName,onClose,onSent}:{meetingUrl:string;meetingTitle:string;hostName:string;onClose:()=>void;onSent?:(label:string)=>void}){
  const [channel,setChannel]=useState<'whatsapp'|'email'|'octa'>('octa'),[destination,setDestination]=useState(''),[sending,setSending]=useState(false),[status,setStatus]=useState('');
  const [selected,setSelected]=useState<string[]>([]);
  const people=demoParticipants.filter(person=>person.role!=='host');
  const message=`${hostName} convidou você para a reunião “${meetingTitle}” na OCTA. Entrar agora: ${meetingUrl}`;
  const togglePerson=(id:string)=>setSelected(items=>items.includes(id)?items.filter(item=>item!==id):[...items,id]);
  const inviteOcta=()=>{if(!selected.length){setStatus('Escolha pelo menos uma pessoa da OCTA.');return}const names=people.filter(p=>selected.includes(p.id)).map(p=>p.displayName);window.dispatchEvent(new CustomEvent('octa-internal-invite',{detail:{participantIds:selected,meetingUrl,meetingTitle,hostName}}));setStatus(`Convite preparado para ${names.join(', ')}.`);onSent?.(`${selected.length} convite(s) OCTA preparado(s)`)};
  async function submit(e:FormEvent){e.preventDefault();setStatus('');if(channel==='octa'){inviteOcta();return}
    if(channel==='whatsapp'){const phone=destination.replace(/\D/g,'');const href=phone?`https://wa.me/${phone}?text=${encodeURIComponent(message)}`:`https://wa.me/?text=${encodeURIComponent(message)}`;window.open(href,'_blank','noopener,noreferrer');onSent?.('Convite aberto no WhatsApp');return}
    if(!destination.includes('@')){setStatus('Digite um e-mail válido.');return}setSending(true);try{const res=await fetch('/api/invitations/email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:destination,meetingUrl,hostName,meetingTitle})});if(res.ok){setStatus('Convite enviado por e-mail.');onSent?.('Convite enviado por e-mail');setDestination('');return}const data=await res.json().catch(()=>({}));if(res.status===503){window.location.href=`mailto:${encodeURIComponent(destination)}?subject=${encodeURIComponent(`Convite OCTA · ${meetingTitle}`)}&body=${encodeURIComponent(message)}`;setStatus('Abrimos seu e-mail para envio imediato.')}else setStatus(data?.error||'Não foi possível enviar o convite.')}finally{setSending(false)}}
  return <div className="fixed inset-0 z-[240] grid place-items-center bg-black/35 p-4 backdrop-blur-sm"><section className="w-full max-w-[470px] rounded-[28px] border border-white/10 bg-[#07131e]/98 p-5 text-white shadow-[0_34px_120px_rgba(0,0,0,.5)]">
    <div className="flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-[.16em] text-cyan-300">Adicionar participantes</p><h3 className="mt-1 text-xl font-semibold">Convidar para esta reunião</h3></div><button onClick={onClose} className="grid size-9 place-items-center rounded-full bg-white/8 text-white/65"><X size={15}/></button></div>
    <div className="mt-5 grid grid-cols-3 gap-2"><button onClick={()=>setChannel('octa')} className={`flex h-11 items-center justify-center gap-2 rounded-[14px] border text-xs ${channel==='octa'?'border-violet-300/35 bg-violet-300/10 text-violet-100':'border-white/8 bg-white/[.03] text-white/55'}`}><UsersRound size={15}/> OCTA</button><button onClick={()=>setChannel('whatsapp')} className={`flex h-11 items-center justify-center gap-2 rounded-[14px] border text-xs ${channel==='whatsapp'?'border-emerald-300/35 bg-emerald-300/10 text-emerald-200':'border-white/8 bg-white/[.03] text-white/55'}`}><MessageCircle size={15}/> WhatsApp</button><button onClick={()=>setChannel('email')} className={`flex h-11 items-center justify-center gap-2 rounded-[14px] border text-xs ${channel==='email'?'border-cyan-300/35 bg-cyan-300/10 text-cyan-200':'border-white/8 bg-white/[.03] text-white/55'}`}><Mail size={15}/> E-mail</button></div>
    {channel==='octa'?<div className="mt-4"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-[.12em] text-white/40">Pessoas na OCTA</span><span className="text-[10px] text-white/35">{selected.length} selecionada(s)</span></div><div className="mt-3 grid grid-cols-4 gap-2">{people.map(person=><button key={person.id} onClick={()=>togglePerson(person.id)} className={`relative overflow-hidden rounded-[16px] border text-left ${selected.includes(person.id)?'border-cyan-300/70 ring-2 ring-cyan-300/15':'border-white/8'}`}><img src={person.avatarUrl} alt={person.displayName} className="aspect-[.78] w-full object-cover"/><span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/90 via-black/45 to-transparent px-2 pb-2 pt-7 text-[9px] font-medium leading-3">{person.displayName}</span>{selected.includes(person.id)&&<span className="absolute right-1.5 top-1.5 grid size-6 place-items-center rounded-full bg-white text-[#07131e]"><Check size={12}/></span>}</button>)}</div><button onClick={inviteOcta} className="mt-4 flex h-12 w-full items-center justify-center gap-2 rounded-[15px] bg-white font-semibold text-[#07131e]"><Send size={15}/> Convidar selecionados</button></div>:<form onSubmit={submit} className="mt-4"><label className="text-[10px] text-white/45">{channel==='whatsapp'?'Número com DDD (opcional)':'E-mail do participante'}<input value={destination} onChange={e=>setDestination(e.target.value)} placeholder={channel==='whatsapp'?'Ex.: 5551999999999':'nome@empresa.com'} className="mt-2 h-12 w-full rounded-[15px] border border-white/10 bg-black/20 px-4 text-sm text-white outline-none placeholder:text-white/25"/></label><div className="mt-3 rounded-[15px] border border-white/7 bg-white/[.025] p-3 text-[10px] leading-5 text-white/45">{message}</div><button disabled={sending} className="mt-4 flex h-12 w-full items-center justify-center gap-2 rounded-[15px] bg-white font-semibold text-[#07131e] disabled:opacity-50"><Send size={15}/>{sending?'Enviando…':'Enviar convite'}</button></form>}
    {status&&<p className="mt-3 rounded-[12px] bg-cyan-300/8 px-3 py-2 text-[11px] text-cyan-100">{status}</p>}
  </section></div>;
}
