'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Calculator, Camera, CameraOff, ChevronDown, Copy, Filter, Heart, LayoutDashboard, MessageCircle, Mic, MicOff, MoreHorizontal, NotebookPen, PhoneOff, Pin, ScreenShare, Send, Sparkles, UserPlus, Users, Volume2, WandSparkles } from 'lucide-react';
import { demoMessages, demoParticipants, currentUser } from '@/lib/demo/data';
import { isLiveKitConfigured } from '@/lib/livekit/config';
import type { Participant } from '@/types/domain';
import { ChatOverlay } from '@/features/chat/chat-overlay';
import { NotesPanel } from '@/features/notes/notes-panel';
import { WhiteboardPanel } from '@/features/whiteboard/whiteboard-panel';
import { LiveKitStage } from './livekit-stage';
import { LocalCameraStage } from './local-camera-stage';
import { MeetingPrejoin } from './meeting-prejoin';
import { MeetingStrategicAI } from './meeting-strategic-ai';
import { PresentationMode } from './presentation-mode';
import { MeetingDraggableCalculator } from '@/components/meeting-draggable-calculator';
import { MeetingDraggableFilter } from '@/components/meeting-draggable-filter';
import { filterCss } from '@/lib/video-filters';
import { GlobalScreenshotButton } from '@/components/global-screenshot-button';

const roleLabel=(role:Participant['role'])=>role==='host'?'anfitrião':role==='cohost'?'coanfitrião':'participante';
export function MeetingClient({slug,title}:{slug:string;title:string}){
 const [people,setPeople]=useState<Participant[]>(demoParticipants);const[selected,setSelected]=useState<string|null>(null);const[focused,setFocused]=useState('u-host');const[chat,setChat]=useState(()=>{try{return localStorage.getItem('octa-chat-enabled')!=='0'}catch{return true}});const[notes,setNotes]=useState(false);const[board,setBoard]=useState(false);const[mic,setMic]=useState(true);const[camera,setCamera]=useState(true);const[joined,setJoined]=useState(false);const[photoUrl,setPhotoUrl]=useState<string|null>(null);const[copyState,setCopyState]=useState('Copiar link');const[calculator,setCalculator]=useState(false);const[filters,setFilters]=useState(false);const[presentationOpen,setPresentationOpen]=useState(false);const[meetingTools]=useState(()=>{try{return localStorage.getItem('octa-meeting-tools')!=='0'}catch{return true}});const[filter,setFilter]=useState('natural');const[intensity,setIntensity]=useState(80);
 const focus=useMemo(()=>people.find(p=>p.id===focused)??people[0],[people,focused]);
 useEffect(()=>()=>{if(photoUrl?.startsWith('blob:'))URL.revokeObjectURL(photoUrl)},[photoUrl]);
 function toggleSpeak(id:string){setPeople(ps=>ps.map(p=>p.id===id?{...p,canSpeak:!p.canSpeak}:p))}function promote(id:string){setPeople(ps=>ps.map(p=>p.id===id?{...p,role:p.role==='cohost'?'participant':'cohost'}:p))}
 async function copyLink(){try{await navigator.clipboard.writeText(window.location.href);setCopyState('Link copiado');window.setTimeout(()=>setCopyState('Copiar link'),1600)}catch{setCopyState('Copie da barra');window.setTimeout(()=>setCopyState('Copiar link'),1600)}}
 if(!joined)return <MeetingPrejoin title={title} cameraEnabled={camera} micEnabled={mic} photoUrl={photoUrl} fallbackPhotoUrl={currentUser.avatarUrl} onCameraChange={setCamera} onMicChange={setMic} onPhotoChange={setPhotoUrl} onJoin={()=>setJoined(true)}/>;
 return <main className="h-[100dvh] overflow-hidden bg-[#efefec] p-2 md:p-3"><div className="relative mx-auto flex h-full max-w-[1700px] overflow-hidden rounded-[34px] border border-black/[.08] bg-[#0a0a0a] shadow-[0_28px_90px_rgba(0,0,0,.16)]">
  <aside className="hidden w-[72px] shrink-0 flex-col items-center border-r border-white/[.06] py-4 lg:flex"><Link href="/" className="grid size-10 place-items-center rounded-2xl bg-white text-black"><Sparkles size={17}/></Link><div className="mt-8 flex flex-col gap-3"><SideIcon active icon={<LayoutDashboard size={17}/>}/><SideIcon icon={<Users size={17}/>}/><SideIcon icon={<MessageCircle size={17}/>} onClick={()=>setChat(x=>!x)}/>{meetingTools&&<><SideIcon icon={<NotebookPen size={17}/>} onClick={()=>setNotes(true)}/><SideIcon icon={<Calculator size={17}/>} onClick={()=>setCalculator(true)}/><SideIcon icon={<Filter size={17}/>} onClick={()=>setFilters(true)}/><SideIcon icon={<WandSparkles size={17}/>} onClick={()=>setBoard(true)}/></>}<Link href="/skills" aria-label="Skills" title="Skills" className="grid size-10 place-items-center rounded-2xl text-white/70 hover:bg-white/10 hover:text-white"><Sparkles size={17}/></Link></div></aside>
  <section className="relative min-w-0 flex-1 p-2 md:p-3"><div className="absolute left-5 right-5 top-5 z-20 flex items-center justify-between"><div className="glass flex items-center gap-3 rounded-full px-3 py-2"><div className="size-2 rounded-full bg-emerald-300 shadow-[0_0_14px_#6effb0]"/><div><div className="max-w-[180px] truncate text-xs font-semibold md:max-w-none md:text-sm">{title}</div><div className="text-[9px] uppercase tracking-[.16em] text-white/35">Sala ao vivo · 9:16</div></div><ChevronDown size={13} className="text-white/35"/></div><div className="flex gap-2"><button onClick={copyLink} className="glass hidden items-center gap-2 rounded-full px-4 py-2 text-xs text-white/65 sm:flex"><Copy size={13}/> {copyState}</button><button className="glass grid size-10 place-items-center rounded-full"><MoreHorizontal size={17}/></button></div></div>
   <div className="flex h-full items-center justify-center gap-3 overflow-hidden pt-16 pb-28 md:pb-24"><div className="meeting-social-stage relative h-full max-h-[820px] min-h-[420px] w-auto max-w-[min(100%,460px)] flex-1 overflow-hidden rounded-[38px] border border-white/10 bg-[#171717] shadow-[0_40px_100px_rgba(0,0,0,.45)]" style={{aspectRatio:'9/16'}}><div className="absolute inset-0" style={{filter:filterCss(filter,intensity),transition:'filter .2s ease'}}>{focus.id===currentUser.id?(isLiveKitConfigured?<LiveKitStage room={slug} identity={currentUser.id} name={currentUser.displayName} micEnabled={mic} cameraEnabled={camera} photoUrl={photoUrl} fallbackPhotoUrl={currentUser.avatarUrl}/>:<LocalCameraStage cameraEnabled={camera} micEnabled={mic} photoUrl={photoUrl} fallbackPhotoUrl={currentUser.avatarUrl}/>):<>{focus.avatarUrl&&<Image src={focus.avatarUrl} alt={focus.displayName} fill priority className="object-cover"/>}<div className="absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-black/30"/></>}</div><div className="absolute left-4 top-5 z-10 flex items-center gap-2 rounded-full border border-white/10 bg-black/28 p-1.5 pr-3 backdrop-blur-xl">{focus.avatarUrl&&<Image src={focus.avatarUrl} alt={focus.displayName} width={34} height={34} className="size-8 rounded-full object-cover"/>}<div><div className="text-[11px] font-semibold">{focus.displayName}</div><div className="text-[9px] text-white/45">ao vivo</div></div></div><div className="absolute bottom-5 left-5 z-10 max-w-[72%]"><div className="text-lg font-semibold">{focus.displayName}</div><div className="text-xs text-white/50">{focus.headline}</div><div className="mt-2 rounded-full bg-black/30 px-3 py-1.5 text-[10px] text-white/72 backdrop-blur-lg">Reunião em andamento · participe da conversa</div></div><div className="absolute right-4 top-5 z-10 flex flex-col gap-2"><span className="rounded-full bg-black/45 px-3 py-1.5 text-[10px] backdrop-blur-lg">9:16</span>{focus.canSpeak&&<span className="grid size-8 place-items-center rounded-full bg-black/45 backdrop-blur-lg"><Volume2 size={13}/></span>}</div><div className="meeting-reaction-rail"><button aria-label="Curtir"><Heart size={18}/><span>128</span></button><button onClick={()=>setChat(true)} aria-label="Comentários"><MessageCircle size={18}/><span>32</span></button><button aria-label="Compartilhar"><Send size={18}/></button></div>{chat&&<ChatOverlay initialMessages={demoMessages} onClose={()=>setChat(false)}/>}</div>
    <div className="hidden h-full max-h-[820px] w-[270px] flex-col rounded-[30px] border border-white/[.08] bg-white/[.035] p-3 xl:flex"><div className="flex items-center justify-between p-2"><div><p className="text-[9px] uppercase tracking-[.16em] text-white/35">Controles do anfitrião</p><h3 className="mt-1 text-sm font-semibold">Participantes</h3></div><UserPlus size={16} className="text-white/35"/></div><div className="no-scrollbar mt-2 flex-1 space-y-2 overflow-y-auto">{people.map(p=><button key={p.id} onClick={()=>setSelected(p.id)} className={`flex w-full items-center gap-3 rounded-2xl p-2 text-left ${selected===p.id?'bg-white/10':'hover:bg-white/[.05]'}`}>{p.avatarUrl&&<Image src={p.avatarUrl} alt={p.displayName} width={42} height={42} className="size-10 rounded-xl object-cover"/>}<div className="min-w-0 flex-1"><div className="truncate text-xs font-semibold">{p.displayName}</div><div className="mt-1 flex items-center gap-1 text-[9px] text-white/35"><span>{roleLabel(p.role)}</span><span>·</span><span>{p.canSpeak?'pode falar':'aguardando'}</span></div></div><span className={`size-2 rounded-full ${p.canSpeak?'bg-emerald-300':'bg-white/15'}`}/></button>)}</div></div></div>
   <div className="absolute bottom-[76px] left-1/2 z-30 w-[calc(100%-26px)] max-w-[780px] -translate-x-1/2 md:bottom-5"><div className="meeting-participant-strip no-scrollbar mb-2 flex items-center gap-2 overflow-x-auto px-1">{people.map(p=><button key={p.id} onClick={()=>setSelected(p.id)} className={`relative shrink-0 rounded-full p-1 ${selected===p.id?'bg-white':'bg-white/10'}`}>{p.avatarUrl&&<Image src={p.avatarUrl} alt={p.displayName} width={50} height={50} className="size-11 rounded-full object-cover"/>}<span className={`absolute bottom-0 right-0 size-3 rounded-full border-2 border-[#0a0a0a] ${p.canSpeak?'bg-emerald-300':'bg-[#474952]'}`}/></button>)}</div>{selected&&<HostActions participant={people.find(p=>p.id===selected)!} onFocus={()=>{setFocused(selected);setSelected(null)}} onSpeak={()=>toggleSpeak(selected)} onPromote={()=>promote(selected)} onClose={()=>setSelected(null)}/>}<div className="glass mx-auto flex w-fit items-center gap-1 rounded-full p-2"><DockButton active={mic} onClick={()=>setMic(x=>!x)} icon={mic?<Mic size={17}/>:<MicOff size={17}/>}/><DockButton active={camera} onClick={()=>setCamera(x=>!x)} icon={camera?<Camera size={17}/>:<CameraOff size={17}/>}/><DockButton onClick={()=>setChat(x=>!x)} icon={<MessageCircle size={17}/>}/>{meetingTools&&<><DockButton onClick={()=>setNotes(true)} icon={<NotebookPen size={17}/>}/><DockButton onClick={()=>setCalculator(true)} icon={<Calculator size={17}/>}/><DockButton onClick={()=>setFilters(true)} icon={<Filter size={17}/>}/><DockButton onClick={()=>setBoard(true)} icon={<WandSparkles size={17}/>}/></>}<DockButton onClick={()=>setPresentationOpen(true)} icon={<ScreenShare size={17}/>}/><Link href="/" className="ml-1 grid size-11 place-items-center rounded-full bg-[#ff4f62] text-white"><PhoneOff size={17}/></Link></div></div>
   {notes&&<NotesPanel roomSlug={slug} meetingTitle={title} onClose={()=>setNotes(false)}/>} {board&&<WhiteboardPanel onClose={()=>setBoard(false)}/>} {filters&&<MeetingDraggableFilter selected={filter} intensity={intensity} onSelect={setFilter} onIntensity={setIntensity} onClose={()=>setFilters(false)}/>} {calculator&&<MeetingDraggableCalculator onClose={()=>setCalculator(false)}/>} 
   <PresentationMode open={presentationOpen} onClose={()=>setPresentationOpen(false)} roomSlug={slug} participants={people.map(p=>({id:p.id,displayName:p.displayName,avatarUrl:p.avatarUrl}))}/><MeetingStrategicAI slug={slug} title={title} participants={people.map(p=>({id:p.id,name:p.displayName}))}/><GlobalScreenshotButton/>
  </section></div></main>
}
function SideIcon({icon,active,onClick}:{icon:React.ReactNode;active?:boolean;onClick?:()=>void}){return <button onClick={onClick} className={`grid size-10 place-items-center rounded-2xl ${active?'bg-white/10 text-white':'text-white/35 hover:text-white'}`}>{icon}</button>}
function DockButton({icon,active=true,onClick}:{icon:React.ReactNode;active?:boolean;onClick?:()=>void}){return <button onClick={onClick} className={`grid size-11 place-items-center rounded-full transition ${active?'bg-white/[.07] text-white':'bg-rose-500/15 text-rose-300'} hover:bg-white/[.13]`}>{icon}</button>}
function HostActions({participant,onFocus,onSpeak,onPromote,onClose}:{participant:Participant;onFocus:()=>void;onSpeak:()=>void;onPromote:()=>void;onClose:()=>void}){return <div className="glass absolute bottom-[76px] left-1/2 flex -translate-x-1/2 flex-wrap items-center justify-center gap-1 rounded-[22px] p-2 text-xs shadow-2xl"><span className="px-3 font-semibold">{participant.displayName}</span><button onClick={onSpeak} className="rounded-full bg-white px-3 py-2 text-black">{participant.canSpeak?'Retirar fala':'Dar a palavra'}</button><button onClick={onFocus} className="flex items-center gap-1 rounded-full px-3 py-2 text-white/65 hover:bg-white/10"><Pin size={12}/> Fixar</button><button onClick={onPromote} className="rounded-full px-3 py-2 text-white/65 hover:bg-white/10">{participant.role==='cohost'?'Remover coanfitrião':'Tornar coanfitrião'}</button><button onClick={onClose} className="rounded-full px-3 py-2 text-white/35">Fechar</button></div>}
