'use client';
import { useRef,useState } from 'react';
import { Activity,Mic2,Square } from 'lucide-react';
import { OctaDigitalMark } from '@/components/ai/octa-digital-mark';
import { saveMeetingAnalysis } from '@/lib/meeting-analysis-store';
import type { MeetingSkillAnalysis } from '@/lib/skills-analysis';

export function MeetingAIInsight({slug,title}:{slug:string;title:string}){
 const[transcript,setTranscript]=useState('');const[listening,setListening]=useState(false);const[loading,setLoading]=useState(false);const[message,setMessage]=useState('A IA avalia apenas o que tiver evidência suficiente.');const[analysis,setAnalysis]=useState<MeetingSkillAnalysis|null>(null);const recognitionRef=useRef<any>(null);
 function toggleListening(){if(listening){recognitionRef.current?.stop?.();setListening(false);return}const w=window as any;const Recognition=w.SpeechRecognition||w.webkitSpeechRecognition;if(!Recognition){setMessage('Seu navegador não oferece transcrição de voz nativa. Você pode colar a transcrição abaixo.');return}const recognition=new Recognition();recognition.lang='pt-BR';recognition.continuous=true;recognition.interimResults=false;recognition.onresult=(event:any)=>{let text='';for(let i=event.resultIndex;i<event.results.length;i++)if(event.results[i].isFinal)text+=`${event.results[i][0].transcript} `;if(text)setTranscript(current=>`${current} ${text}`.trim())};recognition.onerror=()=>{setListening(false);setMessage('A captura de voz foi interrompida. Você ainda pode analisar o texto já capturado.')};recognition.onend=()=>setListening(false);recognition.start();recognitionRef.current=recognition;setListening(true);setMessage('Capturando sua fala para análise. Nada recebe nota sem evidência suficiente.')}
 async function analyze(){if(transcript.trim().length<80){setMessage('Capture ou cole um pouco mais da conversa antes de analisar.');return}setLoading(true);setMessage('Analisando clareza, objetividade, perguntas, argumentação e outras Skills...');try{const response=await fetch('/api/ai/analyze-meeting',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({meetingId:slug,meetingTitle:title,transcript})});const data=await response.json();if(!response.ok){setMessage(data.message||'Não foi possível analisar esta reunião.');return}const next=data.analysis as MeetingSkillAnalysis;saveMeetingAnalysis(next);setAnalysis(next);setMessage(next.summary);fetch('/api/skills/analyses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)}).catch(()=>{})}catch{setMessage('A análise ficou indisponível, mas a reunião continua normalmente.')}finally{setLoading(false)}}
 const best=analysis?.metrics.filter(m=>m.evidenceSufficient&&typeof m.score==='number').sort((a,b)=>(b.score??0)-(a.score??0))[0];
 return <aside className="meeting-ai-insight"><header><div><OctaDigitalMark size={24}/><span>IA · leitura da reunião</span></div><Activity size={14}/></header><p>{message}</p><textarea value={transcript} onChange={e=>setTranscript(e.target.value)} placeholder="Transcrição da sua fala aparece aqui ou pode ser colada..."/><button onClick={toggleListening} type="button">{listening?<><Square size={12} className="inline mr-1"/>Parar captura</>:<><Mic2 size={12} className="inline mr-1"/>Capturar minha fala</>}</button><button onClick={analyze} disabled={loading} type="button">{loading?'Analisando...':'Analisar e atualizar Skills'}</button>{analysis&&<div className="meeting-ai-result"><strong>{analysis.overallScore??'—'}</strong><span>/100 geral</span>{best&&<p>Melhor evidência: {best.label} {best.score}/100 · {best.recommendation}</p>}</div>}</aside>
}
